### ISSUE TITLE
provide some examples

### ISSUE THREAD

**Issue by lucasjinreal** [ModelTC/lightllm#10]
hi, would consider provide some examples running with cli?

**Comment by shihaobai** [comment]
As described in our Readme, after installing LightLLM, you can start the service by running the following command:
python -m lightllm.server.api_server --model_dir /path/llama-7B --tp 1 --max_total_token_num 120000

**Comment by lucasjinreal** [comment]
as I requested in question, wanna calling lightllm API with cli.
