### ISSUE TITLE
[BUG] chatglm2使用lightllm框架进行推理结果差异大

### ISSUE THREAD

**Issue by yubuyuabc** [ModelTC/lightllm#101]
url = 'http://localhost:8080/generate'
headers = {'Content-Type': 'application/json'}
data = {
    'inputs': '你好,寫一千字的告別小作文',
    "parameters": {
        'do_sample': False,
        'ignore_eos': True,
        'max_new_tokens': 2048,
    }
}
response = requests.post(url, headers=headers, data=json.dumps(data))

{'generated_text': ['\n\n你好，親愛的家人、朋友和同事，\n\n今天，我們要離開這個家，\n\n在這個過程中，我們學習到了很多，\n\n我們嘗試過很多不同的活動，\n\n我們體驗到不同的文化和風俗，\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n*500]}
用时66s，且生成很多\n，而原始chatglm2生成500字大概十秒，生成内容如下：
 你好!

在这个离别的时刻,我想对你说声再见。我们经历了许多美好的时光,也经历了许多挑战和困难。但是,无论我们经历了什么,我们都应该珍惜彼此在一起的时间,并感激彼此的陪伴。

我还记得我们第一次见面的场景。那时,我还是一个年轻的学生,而你则是一个已经工作的社会人士。我们在同一个学校学习,但我并没有意识到我们会有未来的联系。然而,随着时间的推移,我们开始变得越来越亲密。我们一起度过了许多美好的时光,分享了彼此的快乐和悲伤。

现在,我们即将分开。我不知道未来会带给我们什么,但我相信我们的友谊会永远持续下去。我们可能会在不同的城市工作或学习,但我们仍然可以保持联系。我们可以通过电话、邮件或社交媒体来分享彼此的生活。我们也可能会遇到新的人和事情,但我们仍然可以保持对彼此的忠诚和信任。

在这个离别的时刻,我想对你说声再见。我会永远珍惜我们的友谊,并希望我们可以在未来的岁月里继续保持联系。祝你一切顺利,未来的生活充满幸福和成功!

**Comment by hiworldwzj** [comment]
@yubuyuabc 你用的是什么显卡呀？

**Comment by yubuyuabc** [comment]
有项目沟通交流的群组嘛

**Comment by hiworldwzj** [comment]
reame里面有个discord 的链接

**Comment by yubuyuabc** [comment]
> 

V100和A100都使用了，生成效果都是这种\n重复，和原始版本差异比较大

**Comment by hiworldwzj** [comment]
@yubuyuabc 理解，请问用的模型的huggingface链接，我们尽快修复这个问题。还有我确认一下你用的官方的那个代码有没有拼接什么其他的prompt的字符串呀，导致输入输出不太一样。

**Comment by yubuyuabc** [comment]
> reame里面有个discord 的链接

我这边试图加入，一直无法接受邀请，链接是否还在有效期呢

**Comment by hiworldwzj** [comment]
@llehtahw 你的链接出问题了

**Comment by yubuyuabc** [comment]
> @yubuyuabc 理解，请问用的模型的huggingface链接，我们尽快修复这个问题。还有我确认一下你用的官方的那个代码有没有拼接什么其他的prompt的字符串呀，导致输入输出不太一样。

原始模型链接为https://huggingface.co/THUDM/chatglm2-6b，并没有拼接任何信息

**Comment by llehtahw** [comment]
WzzfwVSguU 长期有效 @yubuyuabc 
有明确的过期报错吗

**Comment by hiworldwzj** [comment]
@shihaobai 处理下这个模型的问题。

**Comment by shihaobai** [comment]
你好，原始模型会在模型自动拼接prompt，可以试一下在请求上加上prompt
`<html>
<body>




def build_stream_inputs(self, tokenizer, query: str, history: List[Tuple[str, str]] = None):
  | if history:
  | prompt = "\n\n[Round {}]\n\n问：{}\n\n答：".format(len(history) + 1, query)
  | input_ids = tokenizer.encode(prompt, add_special_tokens=False)
  | input_ids = input_ids[1:]
  | inputs = tokenizer.batch_encode_plus([(input_ids, None)], return_tensors="pt", add_special_tokens=False)
  | else:
  | prompt = "[Round {}]\n\n问：{}\n\n答：".format(len(history) + 1, query)
  | inputs = tokenizer([prompt], return_tensors="pt")
  | inputs = inputs.to(self.device)
  | return inputs
 

<br class="Apple-interchange-newline">
</body>
</html>`

**Comment by shihaobai** [comment]
@yubuyuabc  你好可以参考下chatglm 的prompt，他的chat 函数会自动加一下prompt
`<html>
<body>




def build_stream_inputs(self, tokenizer, query: str, history: List[Tuple[str, str]] = None):
  | if history:
  | prompt = "\n\n[Round {}]\n\n问：{}\n\n答：".format(len(history) + 1, query)
  | input_ids = tokenizer.encode(prompt, add_special_tokens=False)
  | input_ids = input_ids[1:]
  | inputs = tokenizer.batch_encode_plus([(input_ids, None)], return_tensors="pt", add_special_tokens=False)
  | else:
  | prompt = "[Round {}]\n\n问：{}\n\n答：".format(len(history) + 1, query)
  | inputs = tokenizer([prompt], return_tensors="pt")
  | inputs = inputs.to(self.device)
  | return inputs
 

<br class="Apple-interchange-newline">
</body>
</html>`

**Comment by shihaobai** [comment]
https://huggingface.co/THUDM/chatglm2-6b/blob/b1502f4f75c71499a3d566b14463edd62620ce9f/modeling_chatglm.py#L1005

**Comment by yubuyuabc** [comment]
> https://huggingface.co/THUDM/chatglm2-6b/blob/b1502f4f75c71499a3d566b14463edd62620ce9f/modeling_chatglm.py#L1005

我这边尽量对齐了prompt和参数，但是差异还是蛮大的
![image](https://github.com/ModelTC/lightllm/assets/58143197/b6df5c07-f47f-4989-9cdc-dd6438c2daec)

**Comment by hiworldwzj** [comment]
@shihaobai

**Comment by shihaobai** [comment]
@yubuyuabc  多谢您指出，我已经修复这个问题了，是重构时引入的一个小bug，可以拉取最新的commit测试一下，在do_sample=False 的情况下，结果完全一致
