### ISSUE TITLE
Performance Issues with huggyllama on H800

### ISSUE THREAD

**Issue by andy-yang-1** [ModelTC/lightllm#104]
I've been experiencing some performance issues when running `llama-7b` on the H800. Specifically, the execution seems slower than expected.

I launched the model with nearly 80GB memory
~~~bash
python -m lightllm.server.api_server \
    --model_dir /path/to/models--huggyllama--llama-7b \
    --tp 1 \
    --max_total_token_num 100000 \
    --max_req_total_len 100000 \
    --max_req_input_len 95000
~~~

and run benchmark serving
~~~bash
python benchmark_serving.py \
    --tokenizer path/to/llama \
    --num-prompts 1000 \
    --dataset ShareGPT_V3_unfiltered_cleaned_split.json
~~~

However, the result is:
~~~bash
total tokens: 494250
Total time: 278.14 s
Throughput: 3.60 requests/s
Average latency: 87.19 s
Average latency per token: 0.27 s
Average latency per output token: 1.26 s
~~~

which is far lower than 10.59 requests/s you mentioned [here](https://github.com/ModelTC/lightllm#service-performance).

Is there anything I am wrong with?

**Comment by hiworldwzj** [comment]
@andy-yang-1  you did not set "--tokenizer_mode auto",  it would use "-tokenizer_mode slow" as default.

**Comment by andy-yang-1** [comment]
@hiworldwzj Thx it worked!
