### ISSUE TITLE
max_total_token_num参数未生效

### ISSUE THREAD

**Issue by HuaYZhao** [ModelTC/lightllm#110]
当我使用bigcode系列的模型时，可以成功加载，并产生正确的结果，但max_total_token_num似乎并未生效，不论我设为多少，服务启动后都只占有模型大小的显存量，当我改为llama模型后，它又重新生效了！请帮忙看一下，谢谢！
模型：WizardCoder-15B（gptbigcode）
显卡：A100

并且我测试了在这种情形下，服务的吞吐能力下降一倍，当我回退为llama时，有明显改善。

**Comment by hiworldwzj** [comment]
@HuaYZhao  这看起来很难以理解，这个 max_total_token_num 的设置生效很简单，是固定的代码，是不是 max_total_token_num 设置得太小了，WizardCoder-15B 这个模型是GQA 的架构吗？

**Comment by HuaYZhao** [comment]
@hiworldwzj 这个模型是MQA架构，与GPT2的区别仅仅是将MHA改为MQA，在我的多次实验中，这个问题一直存在，不知道是否在你们的环境中存在？

**Comment by hiworldwzj** [comment]
@HuaYZhao MQA的话，我估计是max_total_token_num 设置得太小了，可以设大些。MQA 容量很大的
