### ISSUE TITLE
lightllm vs vllm

### ISSUE THREAD

**Issue by Cydia2018** [ModelTC/lightllm#114]
docs/LightLLM.md中的图片表明lightllm的吞吐是vllm的2-3x，图片中vllm的版本是v0.2.1，但是vllm官方仓库目前是0.1.4，请问是否是笔误呢？
![](https://github.com/ModelTC/lightllm/raw/main/docs/LightLLM/Untitled%205.png)

期待您的回答。

**Comment by hiworldwzj** [comment]
@Cydia2018 感谢勘误，这个应该是小伙伴写错了，应该是0.1.2
