### ISSUE TITLE
Specification of Mixed Long and Short Requests in Efficient Router Benchmark

### ISSUE THREAD

**Issue by JiankunW** [ModelTC/lightllm#115]
Hi,

Thank you for your excellent work. I have been studying the LightLLM.md documentation and came across the mention that the performance of Efficient Router improves with requests that have large differences in question lengths. I'm interested in learning more about the specification of this new benchmark dataset and how the difference in request lengths may influence performance improvement.

Questions:

1. The specification of the benchmark dataset. How "greater difference" is.
2. Any insights regarding how might the varying question length distribution achieve performance improvements.

**Comment by shihaobai** [comment]
Thanks for your attention! The output length of the benchmark dataset is ranging from 32 to 1024.  Moreover, our router determines whether to add new requests based on the total amount of tokens the system can hold at each future time point,   thus reducing the queuing time relative to the previous approach
