### ISSUE TITLE
[Feature Request] Support stop sequences

### ISSUE THREAD

**Issue by yunfeng-scale** [ModelTC/lightllm#124]
Stop sequences is a must for production usage. It looks like with the current architecture this is not trivial to implement. I suppose after getting tokenized texts, if it's a stop sequence, the httpserver process could send a special signal to router to let it stop processing the request.

**Comment by hiworldwzj** [comment]
@yunfeng-scale Hello, I want to confirm if the eos_id still takes effect when the stop sequences is activated.？

**Comment by yunfeng-scale** [comment]
`eos_id` should still take effect. to disable the effect of `eos_id` there could be a new flag.

**Comment by hiworldwzj** [comment]
@yunfeng-scale  This feature has already been implemented in #137 . you can try it.
