### ISSUE TITLE
为什么 chatglm2 使用 tokenizer_mode auto 没有效果？

### ISSUE THREAD

**Issue by yuanphoenix** [ModelTC/lightllm#129]
命令是

`python3 -m lightllm.server.api_server --port 7456 --tp 1 --trust_remote_code --tokenizer_mode auto  --max_total_token_num 120000
`
结果依然出现 

```
2023-09-12 21:26:45.028 | INFO     | lightllm.server.tokenizer:get_tokenizer:39 - auto
2023-09-12 21:26:45.030 | INFO     | lightllm.server.tokenizer:get_tokenizer:45 - 模式是auto
Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
```

**Comment by hiworldwzj** [comment]
@yuanphoenix 可能是你的模型目录下没有 fast tokenizer 对应的文件，你可以查看一些资料，自己生成一个。

**Comment by yuanphoenix** [comment]
发现 chatglm2 并没有 tokenizer.json 文件，再者发现encode和decode的过程是在主进程和一个子进程上进行的。推理是另一个子进程，编解码的速度似乎没有多重要。
