### ISSUE TITLE
不好意思想請問各位大神~小弟是剛接觸的新手~想知道為何沒辦法install triton?

### ISSUE THREAD

**Issue by WesissoNB** [ModelTC/lightllm#138]
不好意思想請問各位大神~小弟是剛接觸的新手~想知道為何沒辦法install triton?

**Comment by hiworldwzj** [comment]
pip install -U --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/Triton-Nightly/pypi/simple/ triton-nightly  直接用这个 2.1.0得lightly版本吧

**Comment by WesissoNB** [comment]
想請問要如何才能實際將自己的文本放入模型中作測試呢?
