### ISSUE TITLE
I have encountered a few issues during installation. Can somebody help me ? Thank you very very much~~

### ISSUE THREAD

**Issue by WesissoNB** [ModelTC/lightllm#146]
I would like to ask for advice from programming experts. I have encountered a few issues during installation:

1.When running 'pip install triton' and 'pip install uvloop', I encounter problems such as 'Could not find a version that satisfies the requirement triton==2.1.0 (from versions: none)' for triton and similar issues for uvloop. Can someone please guide me on how to resolve these issues?

2.When I run 'python setup.py install' in the command prompt, it doesn't produce any results. I'm a beginner in programming, so I would greatly appreciate any help. 

Thank you very much~~

**Comment by hiworldwzj** [comment]
@WesissoNB You can ignore this errors, and use " pip install xxx --no-deps" to install packages.

**Comment by WesissoNB** [comment]
Thank you very much~~I'll give it a try later :)
