### ISSUE TITLE
关于启动server，404报错的问题

### ISSUE THREAD

**Issue by cjt0** [ModelTC/lightllm#152]
INFO:     Started server process [198]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     10.122.166.168:46232 - "POST /xxl-job-admin/api/registry HTTP/1.1" 404 Not Found
INFO:     10.122.166.168:46828 - "POST /xxl-job-admin/api/registry HTTP/1.1" 404 Not Found
INFO:     10.122.166.168:47510 - "POST /xxl-job-admin/api/registry HTTP/1.1" 404 Not Found
INFO:     10.122.166.168:48148 - "POST /xxl-job-admin/api/registry HTTP/1.1" 404 Not Found
INFO:     10.122.166.168:48846 - "POST /xxl-job-admin/api/registry HTTP/1.1" 404 Not Found

**Comment by hiworldwzj** [comment]
@cjt0 目前没有提供这个接口 "POST /xxl-job-admin/api/registry HTTP/1.1"。

**Comment by cjt0** [comment]
@hiworldwzj 请问这是什么意思，我没做修改，启动服务就一直报这个错误

**Comment by hiworldwzj** [comment]
@cjt0 是不是有什么脚本，一直在往这个端口发请求。

**Comment by hiworldwzj** [comment]
@cjt0 你把启动的绑定端口换一下把。

**Comment by cjt0** [comment]
@hiworldwzj 问题解决了，但是出现了个新异常，RuntimeError: Triton Error [CUDA]: invalid argument，看其他issue应该是lightllm不支持t4卡。
