### ISSUE TITLE
LlamaTpPartModelQuantized mode=['int8weight']测速明显慢于Llama2TpPartModel

### ISSUE THREAD

**Issue by HIT-cwh** [ModelTC/lightllm#157]
**Before you submit an issue, please search for existing issues to avoid duplicates.**

**Issue description:**

非常感谢你们的开源工作！有个问题想请教下。我想调用LlamaTpPartModelQuantized对llama2 w8a8模型进行测速，但发现w8a8的推理速度远慢于fp16。不知道是不是我哪里搞错了。

**Steps to reproduce:**

1. 修改test/model/test_llama2.py的代码为以下代码
```diff
import os
import sys
import unittest
from model_infer import test_model_inference
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

class TestLlama2Infer(unittest.TestCase):

-    def test_llama2_infer(self):
-        from lightllm.models.llama2.model import Llama2TpPartModel
-        test_model_inference(world_size=8, 
-                             model_dir="/mnt/llama2/huggingface/llama-2-7b", 
-                             model_class=Llama2TpPartModel, 
-                             batch_size=20, 
-                             input_len=1024, 
-                             output_len=1024)
-         return
    
+    def test_llama2_quant_infer(self):
+        from lightllm.models.llama_quantized.model import LlamaTpPartModelQuantized
+        test_model_inference(world_size=1, 
+                             model_dir="/mnt/llama2/huggingface/llama-2-7b", 
+                             model_class=LlamaTpPartModelQuantized, 
+                             mode=['int8weight'],
+                             batch_size=20, 
+                             input_len=1024, 
+                             output_len=1024)
+        return


if __name__ == '__main__':
    unittest.main()
```
2. 运行python test/model/test_llama2.py

**Expected behavior:**

fp16的测速结果如下
![image](https://github.com/ModelTC/lightllm/assets/41630003/67e69a62-0b66-4afc-92f9-b67718c3a992)
w8a8的结果如下
![image](https://github.com/ModelTC/lightllm/assets/41630003/4252e9fe-a5c1-4e33-9629-4a2c7294139d)

**Environment:**

Please provide information about your environment, such as:

- [ ] Using container

- OS: CentOS7
- GPU info:
  - `nvidia-smi` CUDA Version: 11.7
  - Graphics cards: (e.g. a100x8)
- Python: Python3.9
  - currently, only python>=3.9 is supported
- LightLLm: 本地运行，尚未安装
- openai-triton: 2.1.0

**Comment by hiworldwzj** [comment]
@HIT-cwh 这个目前主要是因为用 triton编写的 int8weight 算子性能不佳，这个功能主要是为了让lightllm可以在一些缺少显存的卡上跑起来，基于cuda的实现还需要一段时间才能适配完成。

**Comment by HIT-cwh** [comment]
好的，感谢回复！
