### ISSUE TITLE
Stream output

### ISSUE THREAD

**Issue by tonylin52** [ModelTC/lightllm#17]
Hi,

This project is awesome! May I ask when would lightllm support stream output? Thanks

**Comment by shihaobai** [comment]
Thanks for your attention! You can test the streaming output based on the following interface：
https://github.com/ModelTC/lightllm/blob/03cb09389b7cf11f245e85fb9c66d11ab1bc5a82/lightllm/server/api_server.py#L78C11-L78C26

**Comment by tonylin52** [comment]
Thanks！

**Comment by tonylin52** [comment]
> Thanks for your attention! You can test the streaming output based on the following interface： https://github.com/ModelTC/lightllm/blob/03cb09389b7cf11f245e85fb9c66d11ab1bc5a82/lightllm/server/api_server.py#L78C11-L78C26

How about model quantization inference？Do you have plans for that?

**Comment by XHPlus** [comment]
Yes. A few powerful quantization solutions will be released soon.

**Comment by tonylin52** [comment]
> Yes. A few powerful quantization solutions will be released soon.

Hope to see it!!!!
