### ISSUE TITLE
[BUG]  /v1/chat/completions接口有bug

### ISSUE THREAD

**Issue by xyfZzz** [ModelTC/lightllm#174]
api_server.py脚本里的/v1/chat/completions接口有bug，213行和241行的这句有问题：
`async for request_output, metadata in results_generator:`
results_generator应该return 3个变量，这里for中只取了两个，导致报错。

另外，想额外问个问题，如果2个不同的请求分别调用的是/generate_stream和/v1/chat/completions两个接口，这两个接口的请求会放到一起做batching吗？

**Comment by hiworldwzj** [comment]
@xyfZzz 对于第二个问题，所有的请求都会放到一起batching。不管是从那个接口进入的。第一问题会尽快修复。
