### ISSUE TITLE
部署qwen14B的时候遇到一个停用词的问题[BUG]

### ISSUE THREAD

**Issue by 18827555809** [ModelTC/lightllm#178]
用openai那个接口的时候，结尾会有一个符号：
![image](https://github.com/ModelTC/lightllm/assets/49331451/411b701a-7cfb-4258-b4c1-9453c8af4b3d)
这是我部署的命令：python -m lightllm.server.api_server --model_dir /root/model_warehouse/qwen/Qwen-14B-Chat   --host 0.0.0.0      --port 6769  --tp 1     --max_total_token_num 9216 --max_req_total_len 9216    --max_req_input_len 8192 --eos_id 151643  --trust_remote_code

怎么去除这个符号呢

**Comment by hiworldwzj** [comment]
@18827555809 或许你可以在拿到结果后做一些字符串操作，去掉这些特殊的标签。

**Comment by 18827555809** [comment]
> @18827555809 或许你可以在拿到结果后做一些字符串操作，去掉这些特殊的标签。

好吧，其实我想从根上把它去掉，也许这是14B和7B不同的地方？我加了停用词但是没起作用
![image](https://github.com/ModelTC/lightllm/assets/49331451/d36147c6-6b64-474e-8e5e-c02dee5bf700)

**Comment by hiworldwzj** [comment]
@18827555809 停用词的含义是，遇到生成这个字符串会停止生成，但是并不代表不会输出哈。所以还是会输出出来。

**Comment by 18827555809** [comment]
> @18827555809 停用词的含义是，遇到生成这个字符串会停止生成，但是并不代表不会输出哈。所以还是会输出出来。

感谢您的回答，如果我想让他完美的不输出这个结尾的话，不通过对结果截取字符串的操作的话，我应该去改哪里

**Comment by 18827555809** [comment]
> @18827555809 停用词的含义是，遇到生成这个字符串会停止生成，但是并不代表不会输出哈。所以还是会输出出来。

感谢，我已经解决了

**Comment by niaoyu** [comment]
> > @18827555809 停用词的含义是，遇到生成这个字符串会停止生成，但是并不代表不会输出哈。所以还是会输出出来。
> 
> 感谢，我已经解决了

你好，请问你的解决方式是？

**Comment by 18827555809** [comment]
> > > @18827555809 停用词的含义是，遇到生成这个字符串会停止生成，但是并不代表不会输出哈。所以还是会输出出来。
> > 
> > 
> > 感谢，我已经解决了
> 
> 你好，请问你的解决方式是？

![image](https://github.com/ModelTC/lightllm/assets/49331451/36687091-08f9-4a60-afe1-05251898dadd)
![image](https://github.com/ModelTC/lightllm/assets/49331451/e2f880ed-e555-4052-a3d7-da46ce50d147)

**Comment by niaoyu** [comment]
> --trust_remote_code

感谢回复。另外，我在增加“or finished”后好像没有生效。
这是输入：
    data = {
        'model': 'qwen-7b-chat',
        'messages': [
            {"role": "user", "content": "世界上第二高的山峰是哪座"}
        ],
        "temperature": 0.7,
        "max_tokens": 512, 
        "temperature": 0.8,  
        "top_p": 0.8,  
        "stop": "<|im_end|>"
    }

增加“or finished”前的输出是这样：
世界上第二高的山峰是乔戈里峰，位于喜马拉雅山脉，海拔8,611米。<|im_end|>
<|endoftext|>

增加“or finished”后的输出是这样：
世界上第二高的山峰是乔戈里峰，位于喜马拉雅山脉，海拔8,611米。<|im_end|>

还是没有完全解决输出带特定字符的问题？

**Comment by niaoyu** [comment]
感谢 已经解决，需要把服务启动命令变为，--eos_id 151645

指名stop_token_id是<|im_end|>"，而不是readme中的151643，"<|endoftext|>"

**Comment by 18827555809** [comment]
是的，需要这些修改。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月1日(周五) 中午12:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ModelTC/lightllm] 部署qwen14B的时候遇到一个停用词的问题[BUG] (Issue #178)




 
感谢 已经解决，需要把服务启动命令变为，--eos_id 151645
 
指名stop_token_id是<|im_end|&gt;"，而不是readme中的151643，"<|endoftext|&gt;"
