### ISSUE TITLE
[BUG] torch==2.0.0 torch.cuda.is_available() return False in latest docker image

### ISSUE THREAD

**Issue by Juelianqvq** [ModelTC/LightLLM#191]
after docker pull and python -m get: 
Warning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (function operator())

**Comment by shihaobai** [comment]
Thanks for your question! Could provide more details about your hardware, such as driver version.

**Comment by shihaobai** [comment]
The default cuda version in docker is CUDA 11.8,  you can try to upgrade your driver.

**Comment by shihaobai** [comment]
It looks like a problem with your cuda driver.   You can refer to https://docs.nvidia.com/deploy/cuda-compatibility/#deployment-consideration-forward to install a newer driver. 515 is not a stable version.
