### ISSUE TITLE
[BUG]提问的时候回答不全。

### ISSUE THREAD

**Issue by 143heyan** [ModelTC/lightllm#192]
启动脚本：CUDA_VISIBLE_DEVICES=1  python -m lightllm.server.api_server --model_dir /share/LLMs/Qwen-14B-Chat/     \
                                     --trust_remote_code   \
                                     --host 0.0.0.0                 \
                                     --port 6666                    \
                                     --tp  1                         \
                                     --max_total_token_num 50000  \
                                     --tokenizer_mode auto   \
                                     --max_req_total_len 4096
启动过程：
Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO:     Started server process [463444]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:6666 (Press CTRL+C to quit)
结果16个字左右被截断：
![image](https://github.com/ModelTC/lightllm/assets/143150794/2088727c-fd3b-4921-bc87-88d5ce73da43)

**Comment by hiworldwzj** [comment]
@143heyan 默认输出长度是 16， 你没有设置输出长度。

**Comment by 143heyan** [comment]
怎么设置输出长度。没看到配置信息。

**Comment by hiworldwzj** [comment]
"max_tokens" : 1000
