### ISSUE TITLE
Llama2 and llama-30b does not work 

### ISSUE THREAD

**Issue by sureshbhusare** [ModelTC/lightllm#2]
- Only able to run llama-7b model , llama2-13b , llama2-70b and llama-30 Failing 
- Using A100 GPU ,  followed the instruction about `triton` dependencies.

```python
Task exception was never retrieved
future: <Task finished name='Task-12' coro=<RouterManager.loop_for_fwd() done, defined at /home/  /lightllm/lightllm/server/router/manager.py:84> exception='cef3986efedb4d1a966c56365091ddde'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/opt/conda/envs/lightllm-infer/lib/python3.10/site-packages/rpyc/core/protocol.py", line 359, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/opt/conda/envs/lightllm-infer/lib/python3.10/site-packages/rpyc/core/protocol.py", line 837, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/home/  /lightllm/lightllm/utils/infer_utils.py", line 49, in inner_func
    result = func(*args, **kwargs)
  File "/home/  /lightllm/lightllm/server/router/model_infer/model_rpc.py", line 67, in exposed_prefill_batch
    return self.forward(batch_id, is_prefill=True)
  File "/home/  /lightllm/lightllm/server/router/model_infer/model_rpc.py", line 104, in forward
    batch: InferBatch = self.cache.pop(batch_id)
KeyError: 'cef3986efedb4d1a966c56365091ddde'
>
Traceback (most recent call last):
  File "/home/  /lightllm/lightllm/server/router/manager.py", line 87, in loop_for_fwd
    await self._step()
  File "/home/  /lightllm/lightllm/server/router/manager.py", line 106, in _step
    await self._prefill_batch(self.running_batch)
  File "/home/  /lightllm/lightllm/server/router/manager.py", line 139, in _prefill_batch
    ans = await asyncio.gather(*rets)
  File "/home/  /lightllm/lightllm/server/router/model_infer/model_rpc.py", line 185, in prefill_batch
    return ans.value
  File "/opt/conda/envs/lightllm-infer/lib/python3.10/site-packages/rpyc/core/async_.py", line 108, in value
    raise self._obj
_get_exception_class.<locals>.Derived: 'cef3986efedb4d1a966c56365091ddde'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/opt/conda/envs/lightllm-infer/lib/python3.10/site-packages/rpyc/core/protocol.py", line 359, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/opt/conda/envs/lightllm-infer/lib/python3.10/site-packages/rpyc/core/protocol.py", line 837, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/home/  /lightllm/lightllm/utils/infer_utils.py", line 49, in inner_func
    result = func(*args, **kwargs)
  File "/home/  /lightllm/lightllm/server/router/model_infer/model_rpc.py", line 67, in exposed_prefill_batch
    return self.forward(batch_id, is_prefill=True)
  File "/home/  /lightllm/lightllm/server/router/model_infer/model_rpc.py", line 104, in forward
    batch: InferBatch = self.cache.pop(batch_id)
KeyError: 'cef3986efedb4d1a966c56365091ddde'
```

**Comment by XHPlus** [comment]
What version of Python did you use?
The recommended version is >= 3.9, as mentioned in the README.

**Comment by sureshbhusare** [comment]
I am using python 3.10

**Comment by hiworldwzj** [comment]
This error has occurred before mainly due to inconsistent behavior of the python rpyc library across different python versions, so it is best to use python==3.9. There may be other reasons as well. Can you give more setting,  we will try to fix this bug.  Thanks.

**Comment by sureshbhusare** [comment]
My setup

- A100 - with Cuda 11.8
- Conda Environment with python 3.10
- Package installation is from requiremens.txt
- Tried Llama and Llama2 in hugging face format)
Let me know if you need any more information

**Comment by hiworldwzj** [comment]
What is your Python startup command for llama2-70B?

**Comment by sureshbhusare** [comment]
‘’’python -m lightllm.server.api_server --model_dir /home/Llama-70B-hf --tp
1 --max_total_token_num 12000 ‘’’

**Comment by hiworldwzj** [comment]
--tp 1 is not ok for llama2-70B， a single A100（80G）can not hold all weights。 Did you remember incorrectly?

**Comment by sureshbhusare** [comment]
I need to check again I think I put  tp 8

**Comment by hiworldwzj** [comment]
thanks，I will try to fix this bug。

**Comment by hiworldwzj** [comment]
@sureshbhusare hello, I use conda to create a env, python == 3.10.0 , packages from requiremens.txt.  and model is llama2-70b-chat,   run with --tp 8 , but everything is ok.    when http server is ok, how did you run to get this error?  Can you give more details ?

**Comment by sureshbhusare** [comment]
Server starts for me too. But when you do curl/python request API call for
generate then above error shows up.

**Comment by hiworldwzj** [comment]
@sureshbhusare Hello, Can you  give me the results of "pip list" in your computer and python detail version like "3.10.**", I will try to reproduce this bug.

**Comment by hiworldwzj** [comment]
@sureshbhusare Hello,  My colleague encountered the same error before, and he said that the error was mainly caused by the failure to initialize the RPC model, which might be due to someone else using the GPU and causing insufficient GPU memory, resulting in an OOM error. However, this error was not caught and handled. You can use "nvidia-smi" to observe whether someone else is using the GPU before starting the service.

**Comment by sureshbhusare** [comment]
@hiworldwzj - No one was using any GPU on that machine. I use python
package  nvitop which shows real time usage of GPU and processes running on
GPU , only lightllm server process were running.

**Comment by hiworldwzj** [comment]
@sureshbhusare  This is very strange，Can you try “python -m lightllm.server.api_server --model_dir /path/llama2-70B --tp 8 --max_total_token_num 1200 ” again ？ change max_total_token_num to 1200.

**Comment by hiworldwzj** [comment]
@sureshbhusare  you can try to modify the source code in
https://github.com/ModelTC/lightllm/blob/main/lightllm/server/router/model_infer/model_rpc.py#L19
use "try ... catch ... "  to catch all exception in  “exposed_init_model“ method to find what happen.

**Comment by sureshbhusare** [comment]
I will try to recreate that tomorrow morning . I remember trying your
suggestion of putt try catch to handle exception  but didn’t land to a
exact error else I would’ve pushed fix .

I will let you know how it goes.

**Comment by hiworldwzj** [comment]
@sureshbhusare Thank you for your patience.  
You also can try add "try ... catch ..." to method "exposed_add_batch" in  https://github.com/ModelTC/lightllm/blob/main/lightllm/server/router/model_infer/model_rpc.py#L53,
exposed_add_batch used to add a running batch to cache.

**Comment by sureshbhusare** [comment]
I was able to make it work using python 3.9 . I have not recreated the
issue using 3.10 yet.

I would like to know if there is any way for single request I could get the
same throughout as for the concurrent requests get. I think most of the
requests considered as batch currently and for single request only 1 batch
token generation happen. Is there parameter for server command to
overcome this issue?

For single request token generation is very slow.

**Comment by hiworldwzj** [comment]
@sureshbhusare hello，I didn't quite understand your question. Currently, in this implementation, the “router” module merges different HTTP requests into a big batch for model inference. The first access may be slower because the OpenAI Triton kernel needs to be compiled and warmed up.  Could you please provide more details about your question?

**Comment by sureshbhusare** [comment]
Sorry about the confusion.

I was testing the inference using concurrent 100 requests and the
throughput is pretty good.

But when I just send single requests and see the token generation it is
very slow.
So is there a way you could bump/set up max batch size even though we just
send single request so that we will get same throughput.

Hope this helps you !!

**Comment by hiworldwzj** [comment]
@sureshbhusare Hello，If I understand correctly, you want to achieve high throughput even when there is only one request? This may not be possible because if there is only one request, only one request will be running in the gpu, and it is not efficient to use the GPU in single request mode.    

others,  I guess that you  want to send many req in one live http connection ?

**Comment by sureshbhusare** [comment]
Yes, you are right.

**Comment by hiworldwzj** [comment]
@sureshbhusare  you want to send many req in one live http connection，Currently, it is not supported, one http connection for one req， but it doesn't seem too difficult to modify the system to add this feature. only need to add a new url interface and code some detail。

**Comment by sureshbhusare** [comment]
I think adding ‘—min_batch_size’ option will help instead. So that many
token’s definitely generate irrespective of number of requests.

**Comment by hiworldwzj** [comment]
@sureshbhusare yeah，you can try it。
