### ISSUE TITLE
[BUG] Baichuan2-7B-Chat模型，Unexpected mma -> mma layout conversion

### ISSUE THREAD

**Issue by jarviszeng-zjc** [ModelTC/lightllm#222]
Baichuan2-7B-Chat模型，v100机器，单卡，启动api server后，发请求，就报错：
```bash
python: /project/lib/Analysis/Allocation.cpp:40: std::pair<llvm::SmallVector<unsigned int>, llvm::SmallVector<unsigned int> > mlir::triton::getCvtOrder(mlir::Attribute, mlir::Attribute): Assertion `!(srcMmaLayout && dstMmaLayout) && "Unexpected mma -> mma layout conversion"'
```

**Steps to reproduce:**
1. pip install -r requirements.txt
2. CUDA_VISIBLE_DEVICES=2 TRANSFORMERS_OFFLINE=1 python -m lightllm.server.api_server --model_dir /models/baichuan-inc/Baichuan2-7B-Chat --trust_remote_code --max_total_token_num 121060 --tokenizer_mode auto --disable_log_stats
3. benchmark_serving.py

**Environment:**
- OS: CentOS7
- GPU info: NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2
- Python: Python 3.10.12
- LightLLm: main分支：afe40549b4066f496bd846f7e93445be74aa4a8b
- openai-triton: 
```
Name: triton
Version: 2.1.0
Summary: A language and compiler for custom Deep Learning operations
```

**Comment by hiworldwzj** [comment]
pip install -U --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/Triton-Nightly/pypi/simple/ triton-nightly

pip install triton==2.0.0.dev20221202   你可以试试这两个版本的triton能不能行，还有把 max_total_token_num  降低到你这个显卡适应的规模。在 docs 目录下有相关如果计算这个参数的说明。

**Comment by jarviszeng-zjc** [comment]
感谢及时回复，使用triton==2.0.0.dev20221202没有问题了，只是降低max_total_token_num不行。
另外这个问题，Triton那边有个issue：https://github.com/openai/triton/issues/1420
