### ISSUE TITLE
Can nccl init port address be exposed to command line interface?

### ISSUE THREAD

**Issue by haoranchen06** [ModelTC/lightllm#25]
https://github.com/ModelTC/lightllm/blob/03cb09389b7cf11f245e85fb9c66d11ab1bc5a82/lightllm/server/router/model_infer/model_rpc.py#L32C9-L32C9

**Comment by hiworldwzj** [comment]
@haoranchen06  Thank you for your suggestion. We will complete it today.

**Comment by hiworldwzj** [comment]
@haoranchen06  latest code has added nccl_port args. you can try it.
