### ISSUE TITLE
LLama 模型支持问题

### ISSUE THREAD

**Issue by freeliuzc** [ModelTC/lightllm#26]
您好，文档上有列出支持 facebook 的 LLama 模型，尝试用 hf 上的其他llama 模型报错
理论上讲 LLama 的模型结构都比较相似，如果想推理 类似 huggyllama/llama-7b、openlm-research/open_llama_7b 这些模型，请问工作量大吗，如果不大的话，需要做些什么改动呢？

**Comment by hiworldwzj** [comment]
其实工作量都不大，目前模型存在的不兼容的问题，大概集中在几个问题上：
1. 模型权重的名称不是很规范，导致按照名称进行加载权重的时候，加载不了。
2. 模型推理的结构有微小的差异，需要修改一些推理部分的代码。
3. 如果用tp 进行分布式多卡推理，目前需要词表大小 和 权重的shape维度是 tp size的整数倍，词表大小 的问题后续会修复，但是权重的shape维度一定要满足约束。

**Comment by hiworldwzj** [comment]
在加一个，config.json 里面的key， 很多时候变化很大，没有对非标准的格式作兼容，你可以手动修改config.json 来兼容。

**Comment by hiworldwzj** [comment]
从目前掌握的信息来看， lightllm的速度优势主要来自于 detokenize 的异步化和router的调度， 其实lightllm 的decode attention算子还有一些性能问题（比 vllm 差一些），但是受制于triton的一些限制和不稳定，目前还没有办法作修复，要想修复这个问题必须使用 cuda c 编程，这与创建 lightllm 的初衷有点违背，不过也很希望大家可以提供一个支持tokenattention 的 decode attention的高效算子实现。

vllm 的 swap/recompute 特性感觉不是特别适合特别大的模型，有时候带来的是很大的劣势，主要猜测可能是PCIE带宽过底的问题。

我们内部做过相对与TGI 最新版本的测试（背后是vllm + tgi 的调度），目前确实是差不多，如果用rust 实现的router， lightllm 吞吐会比 tgi 高一点，总的来说，我们目前的调度算法是比较有优势的，并且后续会更新一个更精细的调度算法来提升性能，但是在算子层面，由于受限于 triton， 目前并不是最高性能的实现，还有提升空间。

**Comment by freeliuzc** [comment]
感谢大佬解答~~
目前 LightLLM 是逐 token 管理，尽量 contiguous，但 infer 次数多了，token 的分布可能会出现间断性比较大的情况，请问这个有尝试过类似  vllm 的 block_size 的做法吗，以少部分的显存浪费换取较为连续的显存分布 + 向量化读取，或许有一些性能提升

**Comment by hiworldwzj** [comment]
因为现在大模型的head_dim 一般是128，而且还有一个比较大的head_num, 所以 一个token的连续数据量是很大一片的，所以一个token的级别进行访问存储也具有很高的连续性，所以带来的性能损失应该是很低的。

尽量 contiguous， 是代码实现中可以减少一些copy。
