### ISSUE TITLE
[BUG]Baichuan2-13B-chat api_server 结果看起来是续写，像是base模型的结果，而不是chat

### ISSUE THREAD

**Issue by ericg108** [ModelTC/lightllm#279]
**Before you submit an issue, please search for existing issues to avoid duplicates.**
Yes, searched

**Issue description:**
使用docker环境构建环境后，启动api_server部署baichuan2-13B-chat模型，使用/generate接口运行，发现response很像是续写。
这个现象在do_sample=true时更明显。

在下面的示例中，基本上回答里都会有**？**开头，基本是续写。
我也检查了我部署的模型是baichuan2-13B-chat模型，和huggingface上的模型文件sha256一致。

请求示例：
`curl http://127.0.0.1:8080/generate  -X POST -d '{"inputs":"世界上第二高的山峰是哪座","parameters":{"max_new_tokens":1024, "frequency_penalty":1}}'     -H 'Content-Type: application/json'`
请求结果：
{"generated_text": ["**?\n**乔戈里峰（Qogir Feng），位于尼泊尔和中国边境，海拔8,586米（28,169英尺），是世界上第二高的山峰。它位于喀喇昆仑山脉，与世界第一高峰珠穆朗玛峰（Mount Everest）相邻。乔戈里峰的名字在藏语中意为“美丽的皇后”。"], "count_output_tokens": 77}

带do_sample示例：
`curl http://127.0.0.1:8080/generate  -X POST -d '{"inputs":"世界上第二高的山峰是哪座","parameters":{"max_new_tokens":1024, "frequency_penalty":1, "do_sample": true}}'  -H 'Content-Type: application/json'`
结果1：
`{"generated_text": ["山?"], "count_output_tokens": 3}`  --- 这个特别明显像是续写
结果2：
`{"generated_text": ["?\n乔戈里峰是世界上第二高的山峰，位于喜马拉雅山脉，海拔8586米。它位于尼泊尔和中国的边界上，是国际确认的第二高峰。"], "count_output_tokens": 37}`

**Steps to reproduce:**

Please list the steps to reproduce the issue, such as:

0. `docker pull ghcr.io/modeltc/lightllm:main`
1. `python -m lightllm.server.api_server --model_dir /opt/models/Baichuan2-13B-Chat \
    --host 0.0.0.0 \
    --port 8080 \
    --tp 1 \
    --max_total_token_num 60000 \
    --trust_remote_code`
2. `curl http://127.0.0.1:8080/generate  -X POST -d '{"inputs":"世界上第二高的山峰是哪座","parameters":{"max_new_tokens":1024, "frequency_penalty":1}}'     -H 'Content-Type: application/json'`

**Expected behavior:**
返回的结果应该是chat式的回答，而不是语言模型式的续写

**Error logging:**
无

**Environment:**

Please provide information about your environment, such as:

- [x] Using container

- OS: (Ubuntu 22.04)
- GPU info:
  - `nvidia-smi` (` NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3`)
  - Graphics cards: (**A800**)
- Python: (**python 3.9.18**)
  - currently, only python>=3.9 is supported
- LightLLm: (git commit-hash)
  - for container: `docker run --entrypoint cat --rm ghcr.io/modeltc/lightllm:main /lightllm/.git/refs/heads/main`
- openai-triton: `pip show triton`
`Name: triton
Version: 2.1.0
Summary: A language and compiler for custom Deep Learning operations
Home-page: https://github.com/openai/triton/
Author: Philippe Tillet
Author-email: phil@openai.com
License:
Location: /opt/conda/lib/python3.9/site-packages
Requires: filelock
Required-by: lightllm
`

**Additional context:**
None

**Language:**

Please use English as much as possible for better communication.

**Comment by hiworldwzj** [comment]
@ericg108 推理系统侧是存粹的文本输入处理的，没有给各个模型添加其对应的prompt格式。所以你需要自己把你的输入 用对应的prompt 格式拼接成符合prompt格式的输入。

**Comment by ericg108** [comment]
@hiworldwzj 非常感谢快速回复！
我把输入改成`"inputs":"[{\"role\": \"user\", \"content\": \"世界上第二高的山峰是哪座\"}]"`这样了，但仍然不对，结果是空的。`{"generated_text": [""], "count_output_tokens": 1}`
请问baichuan的prompt有例子吗，谢谢！

**Comment by hiworldwzj** [comment]
@ericg108 prompt 不是这样的json格式的，你要瞅瞅 baichuan 在 官方的仓库下的裸推理代码，看他是怎么把你上面的json字符串的内容拼接成一个prompt 字符串的。

**Comment by ericg108** [comment]
@hiworldwzj 好的，谢谢~我去找找

**Comment by ericg108** [comment]
https://github.com/baichuan-inc/Baichuan2/issues/227 这个issue里介绍了怎么拼接为baichuan原生的prompt
