### ISSUE TITLE
OOM when prompt length exceeds 1020.

### ISSUE THREAD

**Issue by tonylin52** [ModelTC/lightllm#28]
Hi,

We deploy llama30b with lightllm, we found that when the length of prompt exceeds 1020, OOM happens.

Enviroment:
1xA100 80G
Driver Version: 460.106.00
Cuda: 11.7
LLaMA 30B

**Comment by tonylin52** [comment]
> @tonylin52 What are your startup parameters?
max_req_input_len=2048
max_req_total_len=3072
max_total_token_num=6000

**Comment by tonylin52** [comment]
The main problem is when OOM happens, there is no error message print for debug.

**Comment by hiworldwzj** [comment]
@tonylin52  Can you give me the oom Python call stack information ?  this will help.

**Comment by tonylin52** [comment]
I update the latest project, everything goes fine!
