### ISSUE TITLE
No module named petrel_client

### ISSUE THREAD

**Issue by Lvjinhong** [ModelTC/lightllm#298]
**Before you submit an issue, please search for existing issues to avoid duplicates.**

**Issue description:**

Please provide a clear and concise description of your issue.

**:**

I encountered the 'No module named petrel_client' error.

I found this code in lightllm/utils/petrel_helper.py.

```
 def _init_petrel(self):
        try:
            from petrel_client.client import Client
            self.client = Client(self.conf_path)
```

But I think petrel_client is not a Python package, and I am confused about the meaning of this code.

Please list the steps to reproduce the issue, such as:

1. `command 0`
2. `command 2`
3. `command 3`

**Expected behavior:**

Please describe what you expected to happen.

**Error logging:**

If applicable, please copy and paste the error message or stack trace here. Use code blocks for better readability.

**Environment:**

Please provide information about your environment, such as:

- [ ] Using container

- OS: (Ubuntu 14.04, CentOS7)
- GPU info:
  - `nvidia-smi` (e.g. `NVIDIA-SMI 525.116.04   Driver Version: 525.116.04   CUDA Version: 12.0`)
  - Graphics cards: (e.g. 4090x8)
- Python: (e.g. CPython3.9)
  - currently, only python>=3.9 is supported
- LightLLm: (git commit-hash)
  - for container: `docker run --entrypoint cat --rm ghcr.io/modeltc/lightllm:main /lightllm/.git/refs/heads/main`
- openai-triton: `pip show triton`

**Additional context:**

Please add any other context or screenshots about the issue here.

**Language:**

Please use English as much as possible for better communication.

**Comment by hiworldwzj** [comment]
@Lvjinhong This is a code for internal use that implements a distributed storage reading method.

**Comment by hiworldwzj** [comment]
@Lvjinhong This code will not affect the normal reading method. You can ignore it.

**Comment by Lvjinhong** [comment]
> @Lvjinhong This code will not affect the normal reading method. You can ignore it.

So is the library open to the public? Is there any way I can install it?

**Comment by wxd000000** [comment]
> > @Lvjinhong This code will not affect the normal reading method. You can ignore it.
> 
> So is the library open to the public? Is there any way I can install it?

This is an internal library we use that's not open-sourced. You can ignore it.

**Comment by Lvjinhong** [comment]
> > > @Lvjinhong This code will not affect the normal reading method. You can ignore it.
> > 
> > 
> > So is the library open to the public? Is there any way I can install it?
> 
> This is an internal library we use that's not open-sourced. You can ignore it.


Thanks, I get it
