### ISSUE TITLE
generate text garbled

### ISSUE THREAD

**Issue by ChristineSeven** [ModelTC/lightllm#31]
When using the llama 2 model to predict "who are you", a bunch of incomprehensible things are generated. The same goes for asking other questions. Does the author know what the problem is?
{u'generated_text': [u"\u868a\n\u987c\u70f9\u4f18\u4f18\u891b\u4f18\u891b\u891b\u4f18\u891b\u4f18\u891b\u4f18\u573b\u4f18\u891b\u891b\u891b\u891b\u891b\u891b\u7d2c\u4f18\u573b\u4f18\u85e6\u891b\u7d2c\u6960\u85e6\u85e6\u85e6\u85e6\u85e6\u85e6\u85e6\u85e6\u85e6\u85e6\u8be0\u8be0\u8be0\u85e6\n\n\u89c9\u62b5\u891b\u752b\u85e6\u85e6\n\u79a4\u6043\u752b\n\u62b5\u85e6\n\u62b5\u85e6\u85e6\u85e6\n\u73b7\u62b5\u85e6\n\u73b7\u62b5\u85e6\n\u73b7\n\u73b7\n\u73b7\n\u73b7\n\u73b7\n\u73b7\n\u73b7\n\u73b7\n\u73b7\n\u73b7\n\u73b7\n\u73b7\n\u73b7\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n\u62b5\u989d\u989d\n'\n'\n'\n'\n'\n\u62b5\u62b5\u85e6\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n\u62b5\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n\u62b5\u989d\u989d\n'\n'\n\u62b5\u989d\n'\n'\n\u62b5\n'\n'\n\u62b5\u989d\u989d\u62b5\n'\n'\n'\n'\n'\n\u62b5\n'\n'\n'\n\u62b5\n'\n'\n'\n\u62b5\n'\n'\n\u62b5\u62b5\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n\u62b5\n'\n'\n'\n'\n'\n'\n\u62b5\n'\n'\n\n\n'\n'\n'\n'\n'\n'\n\u62b5\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n''\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n'\n''\n'\n'\n'\n'\n'\n'''\n'\n'\n'''\n'\n'\n'\n'\n'\n''''\n'\n'\n''\n'\n''''\n'\n'\n''\n'\n'\n''\n'\n'\n'\n'\n'\n'''''\n'\n'''\n"]}

**Comment by hiworldwzj** [comment]
@ChristineSeven  Can you give me your model huggingface link, We will try it.  And Gpu info ?

**Comment by HuaYZhao** [comment]
I used llama-7b-hf to type promprt: "这个世界谁最重要？";Generates garbled{"generated_text": ["\n\u8fd9\u4e2a\u4e16\u754c\ufffd\ufffd\u6700\u91cd\u8981\uff1f 2017-09-28 16:00:00\n\u8fd9\u4e2a\u4e16\u754c\ufffd\ufffd\u6700\u91cd\u8981\uff1f 2017-"]};
I locate that this is because when decoding a single token_id, some, such as Chinese characters, need 2 to 3 token_id to decode into a correct character

**Comment by hiworldwzj** [comment]
@HuaYZhao Thanks, We will fix this tomorrow. it look like a encode question.

**Comment by ChristineSeven** [comment]
@hiworldwzj @HuaYZhao Thanks for reply.
GPU info :Tesla V100, 
model:Llama-2-7b-hf

**Comment by HuaYZhao** [comment]
@hiworldwzj  Additional, huggingface transformers.TextStreamer class seems can serve as a reference, look forward to your latest submission!

**Comment by hiworldwzj** [comment]
> @hiworldwzj @HuaYZhao Thanks for reply. GPU info :Tesla V100, model:Llama-2-7b-hf, link: meta-llama/Llama-2-7b-hf

Hello, Although the V100 graphics card can run LightLLM, there are accuracy issues with the Triton kernel for context_flash_attention, so it currently cannot be supported properly.

**Comment by shihaobai** [comment]
@HuaYZhao Thank for your pointing out! We have fixed the problem.

**Comment by HuaYZhao** [comment]
> I used llama-7b-hf to type promprt: "这个世界谁最重要？";Generates garbled{"generated_text": ["\n\u8fd9\u4e2a\u4e16\u754c\ufffd\ufffd\u6700\u91cd\u8981\uff1f 2017-09-28 16:00:00\n\u8fd9\u4e2a\u4e16\u754c\ufffd\ufffd\u6700\u91cd\u8981\uff1f 2017-"]}; I locate that this is because when decoding a single token_id, some, such as Chinese characters, need 2 to 3 token_id to decode into a correct character

Thank you very much for your active work, but after testing, I found that there are still problems. I think it is not only a string encoding problem, but the fundamental reason is that the model tokenizer may require multiple token_id to be passed in at the same time when decoding characters, so as to decode the correct characters, especially in the case of Chinese. Here are transformers. TextStreamer part of the code references, hope this code will produce for you help

 
```
    def __init__(self, tokenizer: "AutoTokenizer", skip_prompt: bool = False, **decode_kwargs):
        self.tokenizer = tokenizer
        self.skip_prompt = skip_prompt
        self.decode_kwargs = decode_kwargs

        # variables used in the streaming process
        self.token_cache = []
        self.print_len = 0
        self.next_tokens_are_prompt = True

    def put(self, value):
        """
        Receives tokens, decodes them, and prints them to stdout as soon as they form entire words.
        """
        if len(value.shape) > 1 and value.shape[0] > 1:
            raise ValueError("TextStreamer only supports batch size 1")
        elif len(value.shape) > 1:
            value = value[0]

        if self.skip_prompt and self.next_tokens_are_prompt:
            self.next_tokens_are_prompt = False
            return

        # Add the new token to the cache and decodes the entire thing.
        self.token_cache.extend(value.tolist())
        text = self.tokenizer.decode(self.token_cache, **self.decode_kwargs)

        # After the symbol for a new line, we flush the cache.
        if text.endswith("\n"):
            printable_text = text[self.print_len :]
            self.token_cache = []
            self.print_len = 0
        # If the last token is a CJK character, we print the characters.
        elif len(text) > 0 and self._is_chinese_char(ord(text[-1])):
            printable_text = text[self.print_len :]
            self.print_len += len(printable_text)
        # Otherwise, prints until the last space char (simple heuristic to avoid printing incomplete words,
        # which may change with the subsequent token -- there are probably smarter ways to do this!)
        else:
            printable_text = text[self.print_len : text.rfind(" ") + 1]
            self.print_len += len(printable_text)

        self.on_finalized_text(printable_text)
```

**Comment by hiworldwzj** [comment]
@HuaYZhao 
1. pip uninstall lightllm
2. download latest code 
try again, We test it is ok Now.

**Comment by hiworldwzj** [comment]
@shihaobai

**Comment by llehtahw** [comment]
> 我重新进行了测试，拉取最新的代码，删除原先的版本，安装完全一致的requirements.txt； ![image](https://user-images.githubusercontent.com/37064550/259603061-1fc73924-260c-4c10-b565-93c7fb8e1708.png) 以上是我的启动命令，使用的模型是来自huggingface：[https://huggingface.co/decapoda-research/llama-7b-hf/tree/main，](https://huggingface.co/decapoda-research/llama-7b-hf/tree/main%EF%BC%8C) 我简单按照如下发送一个请求，如下所示： ![image](https://user-images.githubusercontent.com/37064550/259603358-388429b4-519a-4b68-a135-d143e1bce673.png) 这似乎并没有解决相应的问题，期待您的回复~

try https://github.com/ModelTC/lightllm/pull/42

**Comment by hiworldwzj** [comment]
@HuaYZhao 这个问题已经解决了，你可以拉取最新的代码试试看。

**Comment by HuaYZhao** [comment]
@hiworldwzj 是的，现在它可以很好的工作了~
