### ISSUE TITLE
int4_kernel

### ISSUE THREAD

**Issue by Cydia2018** [ModelTC/lightllm#324]
请问作者们，lightllm_ppl_int4_kernel和lightllm_lmdeploy_kernel的源码在哪里，我似乎没有在本仓库里找到他们的源代码，非常感谢。

**Comment by hiworldwzj** [comment]
@Cydia2018 有些算子是没有开源的，不过有些算子想学习可以去 https://github.com/hiworldwzj/ppl.llm.kernel.cuda 和 https://github.com/InternLM/lmdeploy/tree/main/src/turbomind/kernels 中查找，相关原理都是相似的。这部分以后可能会考虑开源部分。
