### ISSUE TITLE
InternLM2-20B不支持

### ISSUE THREAD

**Issue by fengenbao** [ModelTC/lightllm#327]
我尝试了一下，目前还不支持这个模型是吗

**Comment by hiworldwzj** [comment]
@fengenbao 应该是支持了的，是不是model type的啥的有点特殊？

**Comment by fengenbao** [comment]
@hiworldwzj 不太行。。。
![image](https://github.com/ModelTC/lightllm/assets/57557769/75f3a409-1b80-4ef8-823b-9f815027362c)

**Comment by hiworldwzj** [comment]
@fengenbao 理论上你把config.json 里面的 model_type internlm2 改成 internlm 应该就可以了。

**Comment by hiworldwzj** [comment]
@fengenbao 后续适配一下对这个interlnlm2 名字的支持。

**Comment by hiworldwzj** [comment]
@fengenbao #328  已经改好了。
