### ISSUE TITLE
[BUG]Benchmark有一些问题

### ISSUE THREAD

**Issue by fengenbao** [ModelTC/lightllm#329]
很久以前我研究vLLM的时候就质疑过这个问题，当时只是自己修改了benchmark里的代码。它里面的output_len是标准答案的长度作为max_new_token，但实际上模型的输出并不完全输出这个长度，可能长也可能短，那应该以实际模型的输出长度作为output_len啊。还有就是吞吐量原本计算num_prompts/benchmark_time也不合适，因为也涉及到输出长度的问题，输出长度长的benchmark_time会很长，吞吐量纸面数据会比较差，但实际上速度并不慢的。

**Comment by hiworldwzj** [comment]
@fengenbao 确实，后续有专用设计的调度算法解决这个问题。
