### ISSUE TITLE
llama-7B一直卡在启动部分

### ISSUE THREAD

**Issue by HalFTeen** [ModelTC/lightllm#35]
如题，拉取最新代码(2023/8/9 14:00), 执行命令：
  python -m lightllm.server.api_server --model_dir ./llm/llama-7b/ --tp 1 --max_total_token_num 6000
我的环境：
OS: centos 7
GPU=1 * 3090 24G。（内存有变化）
python=3.10.12
llama-7b-hf=https://huggingface.co/decapoda-research/llama-7b-hf/tree/main
torch=1.13.0+cu117（如果用2.0.0，运行时会报错：OSError: dlopen: cannot load any more object with static TLS）
cuda=/usr/local/cuda-11.6/（11.7也不行）

期待回复。谢谢

**Comment by hiworldwzj** [comment]
@HalFTeen Hello, 我们最新的代码已经修复了这种类似的问题了，不过目前我们的最优环境可能是 python3.9 + cuda 11.8，然后启动有时候加载tokenizer确实比较慢。理论上 3090 的核心是安培架构，是应该可以跑的。

**Comment by hiworldwzj** [comment]
@HalFTeen 如果GPU内存有变化是在加载模型权重，加载过程是先加载 tokenizer，然后再加载模型，这两个过程可能都比较慢。不知道你说的卡住的时候，gpu的现存是否还会发生变化。

**Comment by HalFTeen** [comment]
@hiworldwzj 我换用了自己编译的cuda11.8，服务正常启动了，但是当测试时候报错：
/usr/bin/ld: 当搜索用于 /usr/lib/libcuda.so 时跳过不兼容的 -lcuda 
/usr/bin/ld: 当搜索用于 /usr/lib/libcuda.so 时跳过不兼容的 -lcuda 
/usr/bin/ld: 当搜索用于 /usr/lib/libcuda.so 时跳过不兼容的 -lcuda 
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<RouterManager.loop_for_fwd() done, defined at /data/wangjie/code/github/lightllm/lightllm/server/router/manager.py:83> exception=CompilationError('at 38:4:\ndef _rotary_kernel(\n    Q, Cos, Sin,\n    stride_qbs, stride_qh, stride_qd,\n    stride_cosbs, stride_cosd,\n    stride_sinbs, stride_sind,\n    max_total_len,\n    H,  # N_CTX 代表要计算的上下文长度\n    BLOCK_HEAD: tl.constexpr,\n    BLOCK_SEQ: tl.constexpr,\n    BLOCK_DMODEL: tl.constexpr,\n):\n    cur_head_index = tl.program_id(0)\n    cur_seq_index = tl.program_id(1)\n\n    cur_head_range = cur_head_index * BLOCK_HEAD + tl.arange(0, BLOCK_HEAD)\n    cur_seq_range = cur_seq_index * BLOCK_SEQ + tl.arange(0, BLOCK_SEQ)\n\n    dim_range0 = tl.arange(0, BLOCK_DMODEL // 2)\n    dim_range1 = tl.arange(BLOCK_DMODEL // 2, BLOCK_DMODEL)\n\n    off_q0 = cur_seq_range[:, None, None] * stride_qbs + cur_head_range[None, :, None] * stride_qh + dim_range0[None, None, :] * stride_qd\n    off_q1 = cur_seq_range[:, None, None] * stride_qbs + cur_head_range[None, :, None] * stride_qh + dim_range1[None, None, :] * stride_qd\n\n    off_dimcos_sin = cur_seq_range[:, None, None] * stride_cosbs + dim_range0[None, None, :] * stride_cosd\n\n    q0 = tl.load(Q + off_q0, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H), other=0.0)\n    q1 = tl.load(Q + off_q1, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H), other=0.0)\n\n    cos = tl.load(Cos + off_dimcos_sin, mask=cur_seq_range[:, None, None] < max_total_len, other=0.0)\n    sin = tl.load(Sin + off_dimcos_sin, mask=cur_seq_range[:, None, None] < max_total_len, other=0.0)\n\n    out0 = q0 * cos - q1 * sin\n    out1 = q0 * sin + q1 * cos\n\n    tl.store(Q + off_q0, out0, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H))\n    tl.store(Q + off_q1, out1, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H))\n\n    return\n    ^')>
Traceback (most recent call last):
  File "<string>", line 21, in _rotary_kernel
KeyError: ('2-.-0-.-0-83ca8b715a9dc5f32dc1110973485f64-d6252949da17ceb5f3a278a70250af13-3b85c7bef5f0a641282f3b73af50f599-3d2aedeb40d6d81c66a42791e268f98b-3498c340fd4b6ee7805fd54b882a04f5-e1f133f98d04093da2078dfc51c36b72-b26258bf01f839199e39d64851821f26-d7c06e3b46e708006c15224aac7a1378-f585402118c8a136948ce0a49cfe122c', (torch.float16, torch.float16, torch.float16, 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'), (4, 32, 128), (True, True, True, (True, False), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (False, False), (True, False)))

**Comment by llehtahw** [comment]
@HalFTeen 这是完整的报错内容吗，后面还有其他报错信息了？

**Comment by HalFTeen** [comment]
@llehtahw 完整的报错信息：
/usr/bin/ld: 当搜索用于 /usr/lib/libcuda.so 时跳过不兼容的 -lcuda 
/usr/bin/ld: 当搜索用于 /usr/lib/libcuda.so 时跳过不兼容的 -lcuda 
/usr/bin/ld: 当搜索用于 /usr/lib/libcuda.so 时跳过不兼容的 -lcuda 
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<RouterManager.loop_for_fwd() done, defined at /data/halfteen/code/github/lightllm/lightllm/server/router/manager.py:83> exception=CompilationError('at 38:4:\ndef _rotary_kernel(\n    Q, Cos, Sin,\n    stride_qbs, stride_qh, stride_qd,\n    stride_cosbs, stride_cosd,\n    stride_sinbs, stride_sind,\n    max_total_len,\n    H,  # N_CTX 代表要计算的上下文长度\n    BLOCK_HEAD: tl.constexpr,\n    BLOCK_SEQ: tl.constexpr,\n    BLOCK_DMODEL: tl.constexpr,\n):\n    cur_head_index = tl.program_id(0)\n    cur_seq_index = tl.program_id(1)\n\n    cur_head_range = cur_head_index * BLOCK_HEAD + tl.arange(0, BLOCK_HEAD)\n    cur_seq_range = cur_seq_index * BLOCK_SEQ + tl.arange(0, BLOCK_SEQ)\n\n    dim_range0 = tl.arange(0, BLOCK_DMODEL // 2)\n    dim_range1 = tl.arange(BLOCK_DMODEL // 2, BLOCK_DMODEL)\n\n    off_q0 = cur_seq_range[:, None, None] * stride_qbs + cur_head_range[None, :, None] * stride_qh + dim_range0[None, None, :] * stride_qd\n    off_q1 = cur_seq_range[:, None, None] * stride_qbs + cur_head_range[None, :, None] * stride_qh + dim_range1[None, None, :] * stride_qd\n\n    off_dimcos_sin = cur_seq_range[:, None, None] * stride_cosbs + dim_range0[None, None, :] * stride_cosd\n\n    q0 = tl.load(Q + off_q0, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H), other=0.0)\n    q1 = tl.load(Q + off_q1, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H), other=0.0)\n\n    cos = tl.load(Cos + off_dimcos_sin, mask=cur_seq_range[:, None, None] < max_total_len, other=0.0)\n    sin = tl.load(Sin + off_dimcos_sin, mask=cur_seq_range[:, None, None] < max_total_len, other=0.0)\n\n    out0 = q0 * cos - q1 * sin\n    out1 = q0 * sin + q1 * cos\n\n    tl.store(Q + off_q0, out0, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H))\n    tl.store(Q + off_q1, out1, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H))\n\n    return\n    ^')>
Traceback (most recent call last):
  File "<string>", line 21, in _rotary_kernel
KeyError: ('2-.-0-.-0-83ca8b715a9dc5f32dc1110973485f64-d6252949da17ceb5f3a278a70250af13-3b85c7bef5f0a641282f3b73af50f599-3d2aedeb40d6d81c66a42791e268f98b-3498c340fd4b6ee7805fd54b882a04f5-e1f133f98d04093da2078dfc51c36b72-b26258bf01f839199e39d64851821f26-d7c06e3b46e708006c15224aac7a1378-f585402118c8a136948ce0a49cfe122c', (torch.float16, torch.float16, torch.float16, 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'), (4, 32, 128), (True, True, True, (True, False), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (False, False), (True, False)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/halfteen/tools/miniconda3/lib/python3.10/site-packages/triton/compiler.py", line 937, in build_triton_ir
    generator.visit(fn.parse())
  File "/data/halfteen/tools/miniconda3/lib/python3.10/site-packages/triton/compiler.py", line 855, in visit
    return super().visit(node)
  File "/data/halfteen/tools/miniconda3/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/data/halfteen/tools/miniconda3/lib/python3.10/site-packages/triton/compiler.py", line 183, in visit_Module
    ast.NodeVisitor.generic_visit(self, node)
  File "/data/halfteen/tools/miniconda3/lib/python3.10/ast.py", line 426, in generic_visit
    self.visit(item)
  File "/data/halfteen/tools/miniconda3/lib/python3.10/site-packages/triton/compiler.py", line 855, in visit
    return super().visit(node)
  File "/data/halfteen/tools/miniconda3/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/data/halfteen/tools/miniconda3/lib/python3.10/site-packages/triton/compiler.py", line 263, in visit_FunctionDef
    fn.reset_type(self.prototype.to_ir(self.builder))
  File "/data/halfteen/tools/miniconda3/lib/python3.10/site-packages/triton/language/core.py", line 298, in to_ir
    ret_types = [ret_type.to_ir(builder) for ret_type in self.ret_types]
  File "/data/halfteen/tools/miniconda3/lib/python3.10/site-packages/triton/language/core.py", line 298, in <listcomp>
    ret_types = [ret_type.to_ir(builder) for ret_type in self.ret_types]
AttributeError: 'NoneType' object has no attribute 'to_ir'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/halfteen/code/github/lightllm/lightllm/server/router/manager.py", line 86, in loop_for_fwd
    await self._step()
  File "/data/halfteen/code/github/lightllm/lightllm/server/router/manager.py", line 105, in _step
    await self._prefill_batch(self.running_batch)
  File "/data/halfteen/code/github/lightllm/lightllm/server/router/manager.py", line 138, in _prefill_batch
    ans = await asyncio.gather(*rets)
  File "/data/halfteen/code/github/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 195, in prefill_batch
    ans = self._prefill_batch(batch_id)
  File "/data/halfteen/code/github/lightllm/lightllm/utils/infer_utils.py", line 49, in inner_func
    result = func(*args, **kwargs)
  File "/data/halfteen/code/github/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 71, in exposed_prefill_batch
    return self.forward(batch_id, is_prefill=True)
  File "/data/halfteen/code/github/lightllm/lightllm/server/router/model_infer/model_rpc.py", line 122, in forward
    logits = self.model.forward(**kwargs)
  File "/data/halfteen/tools/miniconda3/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/halfteen/code/github/lightllm/lightllm/models/llama/layer_infer/model.py", line 113, in forward
    predict_logics = self._context_forward(input_ids, infer_state)
  File "/data/halfteen/code/github/lightllm/lightllm/models/llama/layer_infer/model.py", line 151, in _context_forward
    input_embs = self.layers_infer[i].context_forward(input_embs, infer_state, self.trans_layers_weight[i])
  File "/data/halfteen/code/github/lightllm/lightllm/models/llama/layer_infer/transformer_layer_inference.py", line 117, in context_forward
    self._context_flash_attention(input_embdings,
  File "/data/halfteen/code/github/lightllm/lightllm/utils/infer_utils.py", line 21, in time_func
    ans = func(*args, **kwargs)
  File "/data/halfteen/code/github/lightllm/lightllm/models/llama/layer_infer/transformer_layer_inference.py", line 67, in _context_flash_attention
    rotary_emb_fwd(q.view(calcu_shape1), infer_state.position_cos, infer_state.position_sin)
  File "/data/halfteen/tools/miniconda3/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/halfteen/code/github/lightllm/lightllm/models/llama/triton_kernel/rotary_emb.py", line 62, in rotary_emb_fwd
    _rotary_kernel[grid](
  File "<string>", line 41, in _rotary_kernel
  File "/data/halfteen/tools/miniconda3/lib/python3.10/site-packages/triton/compiler.py", line 1621, in compile
    next_module = compile(module)
  File "/data/halfteen/tools/miniconda3/lib/python3.10/site-packages/triton/compiler.py", line 1550, in <lambda>
    lambda src: ast_to_ttir(src, signature, configs[0], constants)),
  File "/data/halfteen/tools/miniconda3/lib/python3.10/site-packages/triton/compiler.py", line 962, in ast_to_ttir
    mod, _ = build_triton_ir(fn, signature, specialization, constants)
  File "/data/halfteen/tools/miniconda3/lib/python3.10/site-packages/triton/compiler.py", line 942, in build_triton_ir
    raise CompilationError(fn.src, node) from e
triton.compiler.CompilationError: at 38:4:
def _rotary_kernel(
    Q, Cos, Sin,
    stride_qbs, stride_qh, stride_qd,
    stride_cosbs, stride_cosd,
    stride_sinbs, stride_sind,
    max_total_len,
    H,  # N_CTX 代表要计算的上下文长度
    BLOCK_HEAD: tl.constexpr,
    BLOCK_SEQ: tl.constexpr,
    BLOCK_DMODEL: tl.constexpr,
):
    cur_head_index = tl.program_id(0)
    cur_seq_index = tl.program_id(1)

    cur_head_range = cur_head_index * BLOCK_HEAD + tl.arange(0, BLOCK_HEAD)
    cur_seq_range = cur_seq_index * BLOCK_SEQ + tl.arange(0, BLOCK_SEQ)

    dim_range0 = tl.arange(0, BLOCK_DMODEL // 2)
    dim_range1 = tl.arange(BLOCK_DMODEL // 2, BLOCK_DMODEL)

    off_q0 = cur_seq_range[:, None, None] * stride_qbs + cur_head_range[None, :, None] * stride_qh + dim_range0[None, None, :] * stride_qd
    off_q1 = cur_seq_range[:, None, None] * stride_qbs + cur_head_range[None, :, None] * stride_qh + dim_range1[None, None, :] * stride_qd

    off_dimcos_sin = cur_seq_range[:, None, None] * stride_cosbs + dim_range0[None, None, :] * stride_cosd

    q0 = tl.load(Q + off_q0, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H), other=0.0)
    q1 = tl.load(Q + off_q1, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H), other=0.0)

    cos = tl.load(Cos + off_dimcos_sin, mask=cur_seq_range[:, None, None] < max_total_len, other=0.0)
    sin = tl.load(Sin + off_dimcos_sin, mask=cur_seq_range[:, None, None] < max_total_len, other=0.0)

    out0 = q0 * cos - q1 * sin
    out1 = q0 * sin + q1 * cos

    tl.store(Q + off_q0, out0, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H))
    tl.store(Q + off_q1, out1, mask=(cur_seq_range[:, None, None] < max_total_len) & (cur_head_range[None, :, None] < H))

    return

**Comment by hiworldwzj** [comment]
@HalFTeen 可以发一下你的权重目录下的所有文件的信息吗。ll 一下， 你这个错误有点像模型权重没有下全的样子。不过还不是很确定。

**Comment by llehtahw** [comment]
@HalFTeen 删掉 https://github.com/ModelTC/lightllm/blob/360eb453a81ea13c560d218c08402477b2f6943f/lightllm/models/llama/triton_kernel/rotary_emb.py#L45 这一行`return`试试。

另外，可以贴一下你的`pip show triton`吗

**Comment by HalFTeen** [comment]
@hiworldwzj 权重链接在环境里，我下载方式是通过点击下载按钮，每个权重大小显示是405M，但是我下载下来是385M，下面是ll的截图：
![image](https://github.com/ModelTC/lightllm/assets/38465161/1f36d7e8-db87-45b1-988e-f7fc34b82735)

**Comment by hiworldwzj** [comment]
@HalFTeen 看起来是ok的，应该是 triton的问题， @llehtahw

**Comment by HalFTeen** [comment]
@llehtahw 注释掉return，还是会报错：段错误（吐核）。下面是triton信息：
Name: triton
Version: 2.0.0
Summary: A language and compiler for custom Deep Learning operations
Home-page: https://github.com/openai/triton/
Author: Philippe Tillet
Author-email: phil@openai.com
License: 
Location: /data/wangjie/tools/miniconda3/lib/python3.10/site-packages
Requires: cmake, filelock, lit, torch
Required-by: 

我想复现上面那个错误，但是现在只报 段错误吐核，没有上面那些日志了。

**Comment by llehtahw** [comment]
你是说，运行命令后立即段错误，没有任何输出吗

**Comment by hiworldwzj** [comment]
triton 版本是不是更换成 readme 中建议得那个版本。

**Comment by llehtahw** [comment]
> triton 版本是不是更换成 readme 中建议得那个版本。

我也确认到，直接用triton==2.0.0是会有`AttributeError: 'NoneType' object has no attribute 'to_ir'`的问题的，删掉`return`后还会报错

@HalFTeen 建议安装readme中的版本。同时我这边用比较新的triton版本 f1512bded 也是可以正常运行的

**Comment by HalFTeen** [comment]
我重新安装了 readme中的 triton==2.0.0.dev20221202：
Name: triton
Version: 2.0.0.dev20221202
Summary: A language and compiler for custom Deep Learning operations
Home-page: https://github.com/openai/triton/
Author: Philippe Tillet
Author-email: phil@openai.com
License: 
Location: /data/wangjie/tools/miniconda3/lib/python3.10/site-packages
Requires: cmake, filelock, torch
Required-by:
但是仍然会报 段错误吐核，请问 能提供f1512bded对应的链接吗？我试下

**Comment by llehtahw** [comment]
https://github.com/openai/triton/tree/f1512bded1934e34f104bf1ac8547e97e24b2fe8

```sh
git clone https://github.com/openai/triton.git
cd triton
git checkout f1512bded
```

需要自行编译

> 我想复现上面那个错误，但是现在只报 段错误吐核，没有上面那些日志了。

不过既然以前那个错误甚至不能复现，也不好确定段错误的问题是否和triton版本有关

**Comment by HalFTeen** [comment]
段错误后，top看到进程还在，显存依然占用。就感觉很奇怪

**Comment by HalFTeen** [comment]
通过gdb 生成的core文件，得到堆栈信息：
```
Core was generated by `python -m lightllm.server.api_server --model_dir /data/wangjie/code/llm/llama-7'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f480e055758 in _int_free (av=0x7f480e382620 <main_arena>, p=0xf2e520, have_lock=0) at malloc.c:3905
3905	malloc.c: 没有那个文件或目录.
(gdb) bt
#0  0x00007f480e055758 in _int_free (av=0x7f480e382620 <main_arena>, p=0xf2e520, have_lock=0) at malloc.c:3905
#1  0x00007f4806f3f352 in __pyx_f_6uvloop_4loop_8UVHandle__free (__pyx_v_self=0x7f46d10fdd20) at uvloop/loop.c:73105
#2  0x00007f4806f6d1a0 in __pyx_f_6uvloop_4loop___uv_close_handle_cb (__pyx_v_handle=0xf2e530) at uvloop/loop.c:77573
#3  0x00007f4807023315 in uv__finish_close (handle=0xf2e530) at src/unix/core.c:307
#4  uv__run_closing_handles (loop=0x61c9c10) at src/unix/core.c:321
#5  uv_run (loop=0x61c9c10, mode=mode@entry=UV_RUN_DEFAULT) at src/unix/core.c:399
#6  0x00007f4806fb0f23 in __pyx_f_6uvloop_4loop_4Loop___run (__pyx_v_self=0x618b200, __pyx_v_mode=UV_RUN_DEFAULT) at uvloop/loop.c:15044
#7  0x00007f4806fb00bc in __pyx_f_6uvloop_4loop_4Loop__close (__pyx_v_self=0x618b200) at uvloop/loop.c:16174
#8  0x00007f4806f5a13b in __pyx_pf_6uvloop_4loop_4Loop_26close (__pyx_v_self=<optimized out>) at uvloop/loop.c:28298
#9  __pyx_pw_6uvloop_4loop_4Loop_27close (__pyx_v_self=<optimized out>, unused=<optimized out>) at uvloop/loop.c:28275
#10 0x00000000005002c4 in method_vectorcall_NOARGS ()
#11 0x00000000004ee071 in _PyEval_EvalFrameDefault ()
#12 0x00000000004fd90f in _PyFunction_Vectorcall ()
#13 0x00000000004f2466 in _PyEval_EvalFrameDefault ()
#14 0x00000000004fd90f in _PyFunction_Vectorcall ()
#15 0x00000000004f04b9 in _PyEval_EvalFrameDefault ()
#16 0x00000000004fd90f in _PyFunction_Vectorcall ()
#17 0x00000000004ee071 in _PyEval_EvalFrameDefault ()
#18 0x00000000005090de in method_vectorcall ()
#19 0x00000000004eecf3 in _PyEval_EvalFrameDefault ()
#20 0x00000000004fd90f in _PyFunction_Vectorcall ()
#21 0x00000000004ee071 in _PyEval_EvalFrameDefault ()
#22 0x00000000004f5fad in _PyObject_FastCallDictTstate.localalias ()
#23 0x0000000000506cc8 in slot_tp_init ()
#24 0x00000000004f6cab in _PyObject_MakeTpCall.localalias ()
#25 0x00000000004f271e in _PyEval_EvalFrameDefault ()
#26 0x00000000004fd90f in _PyFunction_Vectorcall ()
#27 0x00000000004f2466 in _PyEval_EvalFrameDefault ()
#28 0x00000000004fd90f in _PyFunction_Vectorcall ()
#29 0x00000000004f2466 in _PyEval_EvalFrameDefault ()
#30 0x00000000004fd90f in _PyFunction_Vectorcall ()
#31 0x00000000004ee071 in _PyEval_EvalFrameDefault ()
#32 0x00000000004fd90f in _PyFunction_Vectorcall ()
#33 0x00000000004edc5f in _PyEval_EvalFrameDefault ()
#34 0x0000000000595062 in _PyEval_Vector ()
#35 0x0000000000594fa7 in PyEval_EvalCode ()
#36 0x000000000059c49d in builtin_exec ()
#37 0x00000000004fdaf4 in cfunction_vectorcall_FASTCALL ()
#38 0x00000000004edc5f in _PyEval_EvalFrameDefault ()
#39 0x00000000004fd90f in _PyFunction_Vectorcall ()
#40 0x00000000004edc5f in _PyEval_EvalFrameDefault ()
#41 0x00000000004fd90f in _PyFunction_Vectorcall ()
#42 0x00000000005b825f in pymain_run_module ()
---Type <return> to continue, or q <return> to quit---
#43 0x00000000005b7d42 in Py_RunMain.localalias ()
#44 0x0000000000588299 in Py_BytesMain ()
#45 0x00007f480dffda85 in __libc_start_main (main=0x588250 <main>, argc=9, argv=0x7ffd81017088, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7ffd81017078) at libc-start.c:269
#46 0x000000000058814e in _start ()
```
按照您提供的方法，得到的结果是：
```
Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO:     Started server process [116913]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
[New Thread 0x7fff52a6d700 (LWP 117108)]
[New Thread 0x7fff5526e700 (LWP 117109)]
[New Thread 0x7fff57a6f700 (LWP 117110)]
[New Thread 0x7fff5a270700 (LWP 117111)]
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7181cd5 in malloc_consolidate (av=av@entry=0x7ffff74af620 <main_arena>) at malloc.c:4074
4074	malloc.c: 没有那个文件或目录.
```

**Comment by llehtahw** [comment]
@HalFTeen  也许可以尝试一下不使用uvloop，或者更换uvloop版本，或者更换python3.9版本。

比较奇怪，我的环境也是python3.10.12，uvloop==0.17.0，一切正常。

@hiworldwzj 有没有什么想法

**Comment by hiworldwzj** [comment]
@llehtahw 我想法不多，就是想nvidia能早点发布一个稳定版本的triton。

**Comment by HalFTeen** [comment]
@llehtahw 你用的权重能分享一下链接吗，我换你的模型试试

**Comment by llehtahw** [comment]
> @llehtahw 你用的权重能分享一下链接吗，我换你的模型试试

https://huggingface.co/huggyllama/llama-7b

**Comment by HalFTeen** [comment]
> > @llehtahw 你用的权重能分享一下链接吗，我换你的模型试试
> 
> https://huggingface.co/huggyllama/llama-7b

尝试了这个权重，demo可以正常运行。可能正如#26提到的，不同llama模型参数名不一致导致的。感谢二位大佬的耐心及时的解答。感谢！

**Comment by HalFTeen** [comment]
> > @llehtahw 你用的权重能分享一下链接吗，我换你的模型试试
> 
> https://huggingface.co/huggyllama/llama-7b

尝试了这个权重，demo可以正常运行。可能正如 #26 提到的，不同llama模型参数名不一致导致的。感谢二位大佬的耐心及时的解答。感谢！
