### ISSUE TITLE
[BUG]Error in llama/triton_kernel/silu_and_mul.py/test_silu_and_mul function due to in-place modification of parameters and Triton kernel error in version 2.0.0

### ISSUE THREAD

**Issue by mivenis** [ModelTC/lightllm#357]
There is an issue in the test_silu_and_mul function in the silu_and_mul.py file. The function modifies the parameter X in place, resulting in incorrect results. Additionally, in Triton version 2.0.0, there is an error with the Triton kernel, whereas it runs correctly in version 2.1.1.

**Comment by hiworldwzj** [comment]
@mivenis Thank you for your feedback. This error may not be easy to fix, so I'll look into whether we need to do some triton version isolation.
