### ISSUE TITLE
[Ask] PageAttention 和 TokenAttention 的对比

### ISSUE THREAD

**Issue by zzb610** [ModelTC/lightllm#379]
请教各位一个问题, TokenAttention 是否就是 PageAttention block_size=1 的特例?

根据 TokenAttention https://github.com/ModelTC/lightllm/blob/main/docs/TokenAttention.md 在这里的描述, TokenAttention 的 KV Cache 是根据 max_total_token_num  pre-allocate 的

而 PageAttention 是根据可用的 GPU Memory pre-allocate 的, 可以参考 https://github.com/vllm-project/vllm/blob/main/vllm/executor/gpu_executor.py#L80C32-L80C60

既然都是 pre-allocate 我理解这样的话两种 attention 实现方法都没有 alloc 和 dealloc 的开销

那么 TokenAttention 相对于 PageAttention 的优势在哪里. 请开发者和各位大佬解答, 非常感谢 !

如果我理解有误, 烦请指出, 同样非常感谢 !

**Comment by hiworldwzj** [comment]
@zzb610 确实可以理解成 block_size =1 的特列，但是 PageAttention 和 TokenAttention 在tensor维度的排列上，和算子实现上都有差别的,所以细节是魔鬼， PageAttenttion 立意的碎片化访问存储效率的问题，在head_dim 128 的这个连续长度上是不那么具有确切性和迫切性（至少大多数nvidia gpu上收益较小），可能还是拼算子实现，能有微弱的优势，但是上一点并发以后，感觉几乎无法体现差别。TokenAttention 的优势可能在于，简单性，扩展性，还有可以精确进行调度估计控制一些细粒度的用户体验上的指标。

**Comment by bingo787** [comment]
> @zzb610 确实可以理解成 block_size =1 的特列，但是 PageAttention 和 TokenAttention 在tensor维度的排列上，和算子实现上都有差别的,所以细节是魔鬼， PageAttenttion 立意的碎片化访问存储效率的问题，在head_dim 128 的这个连续长度上是不那么具有确切性和迫切性（至少大多数nvidia gpu上收益较小），可能还是拼算子实现，能有微弱的优势，但是上一点并发以后，感觉几乎无法体现差别。TokenAttention 的优势可能在于，简单性，扩展性，还有可以精确进行调度估计控制一些细粒度的用户体验上的指标。

那文档是不是要更新下？
