### ISSUE TITLE
`grid` in `context_attention_fwd_no_prompt_cache`

### ISSUE THREAD

**Issue by liyucheng09** [ModelTC/lightllm#381]
I found the `grid` in `context_attention_fwd_no_prompt_cache` is defined [here](https://github.com/ModelTC/lightllm/blob/78047d1a8c094e991465334ab5417447291a3478/lightllm/models/llama/triton_kernel/context_flashattention_nopad.py#L307) as:
```
grid = (batch, head, triton.cdiv(max_input_len, BLOCK))
```

However, shouldn't the actual number of token be used here instead of the `max_input_len`?

something like this:

```
grid = (batch, head, triton.cdiv(b_seq_len.sum(), BLOCK))
```

Do we have specific consideration to use `max_input_len` here?

**Comment by hiworldwzj** [comment]
The grid you mentioned requires adjusting the implementation of the kernel. There is a similar case of this in the triton_gqa_flashdecoding mode.
