### ISSUE TITLE
RuntimeError: CUDA: Error- invalid source

### ISSUE THREAD

**Issue by ChristineSeven** [ModelTC/lightllm#39]
GPU info: NVIDIA A800 
model: Llama-2-7b-hf

root@23-0-0-175:/code# python -m lightllm.server.api_server --model_dir /code/Llama-2-7b-hf --tp 1 --max_total_token_num 4096
Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO:     Started server process [35]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<RouterManager.loop_for_fwd() done, defined at /opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/manager.py:84> exception=RuntimeError('CUDA: Error- invalid source')>
Traceback (most recent call last):
  File "<string>", line 21, in _rms_norm_fwd_fused
KeyError: ('2-.-0-.-0-d82511111ad128294e9d31a6ac684238-2b0c5161c53c71b37ae20a9996ee4bb8-c1f92808b4e4644c1732e8338187ac87-d962222789c30252d492a16cca3bf467-12f7ac1ca211e037f62a7c0c323d9990-5c5e32ff210f3b7f56c98ca29917c25e-06f0df2d61979d629033f4a22eff5198-0dd03b0bd512a184b3512b278d9dfa59-d35ab04ae841e2714a253c523530b071', (torch.float16, torch.float16, torch.float16, 'i32', 'i32', 'fp32'), (16384,), (True, True, True, (True, False), (True, False), (False,)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/manager.py", line 87, in loop_for_fwd
    await self._step()
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/manager.py", line 106, in _step
    await self._prefill_batch(self.running_batch)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/manager.py", line 139, in _prefill_batch
    ans = await asyncio.gather(*rets)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/model_infer/model_rpc.py", line 182, in prefill_batch
    ans = self._prefill_batch(batch_id)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/utils/infer_utils.py", line 49, in inner_func
    result = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/model_infer/model_rpc.py", line 67, in exposed_prefill_batch
    return self.forward(batch_id, is_prefill=True)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/server/router/model_infer/model_rpc.py", line 118, in forward
    logits = self.model.forward(**kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/models/llama2/layer_infer/model.py", line 105, in forward
    predict_logics = self._context_forward(input_ids, infer_state)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/models/llama2/layer_infer/model.py", line 143, in _context_forward
    input_embs = self.layers_infer[i].context_forward(input_embs, infer_state, self.trans_layers_weight[i])
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/models/llama2/layer_infer/transformer_layer_inference.py", line 111, in context_forward
    self._context_flash_attention(input_embdings,
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/utils/infer_utils.py", line 21, in time_func
    ans = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/models/llama2/layer_infer/transformer_layer_inference.py", line 57, in _context_flash_attention
    input1 = rmsnorm_forward(input_embding, weight=layer_weight.input_layernorm, eps=self.layer_norm_eps_)
  File "/opt/conda/lib/python3.10/site-packages/lightllm-1.0.0-py3.10.egg/lightllm/models/llama/triton_kernel/rmsnorm.py", line 59, in rmsnorm_forward
    _rms_norm_fwd_fused[(M,)](x_arg, y, weight,
  File "/opt/conda/lib/python3.10/site-packages/triton/runtime/jit.py", line 106, in launcher
    return self.run(*args, grid=grid, **kwargs)
  File "<string>", line 41, in _rms_norm_fwd_fused
  File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 1268, in compile
    return CompiledKernel(name, so_cache_manager._make_path(so_name), fn_cache_manager.cache_dir, device)
  File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 1301, in __init__
    mod, func, n_regs, n_spills = _triton.code_gen.load_binary(metadata["name"], self.asm["cubin"], self.shared, device)
RuntimeError: CUDA: Error- invalid source

**Comment by ChristineSeven** [comment]
cuda version： 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

**Comment by hiworldwzj** [comment]
@ChristineSeven  pip show triton?

**Comment by ChristineSeven** [comment]
@hiworldwzj  
triton                   2.0.0.dev20221202

**Comment by hiworldwzj** [comment]
@ChristineSeven 
see this issue in triton,  https://github.com/openai/triton/issues/1047
you can try "rm -rf ~/.triton" and run again.

if errors runs again,
I suggest that: update gpu driver version, use python==3.9 and cuda==11.8 should be ok.

**Comment by ChristineSeven** [comment]
@hiworldwzj Thanks. How much inference effect it could be improved? I mean effect not performance. Have you done some test?

**Comment by hiworldwzj** [comment]
@ChristineSeven We developed lightllm on A800, and the testing on A800 was extensive. Therefore, the error you encountered is most likely due to an environmental issue.

**Comment by ChristineSeven** [comment]
@hiworldwzj 

cuda version:
vcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
python:
Python 3.9.17

triton:
Version: 2.0.0.dev20221202

For Llama-2-7b-hf,  report error 

python -m lightllm.server.api_server --model_dir /code/Llama-2-7b-hf --tp 1 --max_total_token_num 12000
Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Process Process-1:
router init state: 'NoneType' object has no attribute 'get' detoken init state: init ok

**Comment by hiworldwzj** [comment]
@ChristineSeven it looks like your model Dir  without  config.json，or something else

**Comment by hiworldwzj** [comment]
@ChristineSeven I will try this model  tomorrow and fix it

**Comment by hiworldwzj** [comment]
@ChristineSeven Can you show your model files? or help to find reason.  I have no right to download this model.

**Comment by XHPlus** [comment]
> 

What does the "effect" you mentioned mean?

**Comment by XHPlus** [comment]
> @hiworldwzj Thanks. How much inference effect it could be improved? I mean effect not performance. Have you done some test?

What does the "effect" you mentioned mean?

**Comment by hiworldwzj** [comment]
@ChristineSeven this bug has been fixed, you can try latest code.

**Comment by ChristineSeven** [comment]
@XHPlus "effect", I mean with the lightllm， would it be smarter than the orginal model？Or the same as the orginal model?

**Comment by ChristineSeven** [comment]
@hiworldwzj Sorry， yesterday I was busy on work, and the machine was used on other things. 
Here is the list of files.
total 38G
-rw-r--r-- 1 qax qax 3.3G Jul 21 10:53 model-00002-of-00002.safetensors
-rw-r--r-- 1 qax qax  715 Jul 21 10:51 compare_bin.py
-rw-r--r-- 1 qax qax  179 Jul 21 10:51 generation_config.json
-rw-r--r-- 1 qax qax  27K Jul 21 10:51 pytorch_model.bin.index.json
-rw-r--r-- 1 qax qax 6.9K Jul 21 10:51 LICENSE.txt
-rw-r--r-- 1 qax qax   21 Jul 21 10:51 added_tokens.json
-rw-r--r-- 1 qax qax 1.8M Jul 21 10:51 tokenizer.json
-rw-r--r-- 1 qax qax 1.2M Jul 21 10:51 Responsible-Use-Guide.pdf
-rw-r--r-- 1 qax qax  435 Jul 21 10:51 special_tokens_map.json
-rw-r--r-- 1 qax qax 251M Jul 21 10:51 comparefp16.log
-rw-r--r-- 1 qax qax 4.7K Jul 21 10:51 USE_POLICY.md
-rw-r--r-- 1 qax qax 6.7G Jul 21 10:51 pytorch_model-00003-of-00003.bin
-rw-r--r-- 1 qax qax  746 Jul 21 10:46 tokenizer_config.json
-rw-r--r-- 1 qax qax 9.3G Jul 21 10:46 model-00001-of-00002.safetensors
-rw-r--r-- 1 qax qax  583 Jul 21 10:40 config.json
-rw-r--r-- 1 qax qax  11K Jul 21 10:40 README.md
-rw-r--r-- 1 qax qax  27K Jul 21 10:01 model.safetensors.index.json
-rw-r--r-- 1 qax qax 9.3G Jul 21 10:01 pytorch_model-00002-of-00003.bin
-rw-r--r-- 1 qax qax 489K Jul 21 09:54 tokenizer.model
-rw-r--r-- 1 qax qax 9.2G Jul 21 09:54 pytorch_model-00001-of-00003.bin
And Thanks for your active work.

**Comment by ChristineSeven** [comment]
@hiworldwzj  it seems not the same issue you fixed about rope_scaling.
Here is a list of config files.
total 30066304
-rw-r--r-- 1 xxx xxx          21 Aug 11 14:54 added_tokens.json
-rw-r--r-- 1 xxx xxx         715 Aug 11 14:54 compare_bin.py
-rw-r--r-- 1 xxx xxx   263079902 Aug 11 14:54 comparefp16.log
-rw-r--r-- 1 xxx xxx         583 Aug 11 14:53 config.json
-rw-r--r-- 1 xxx xxx         179 Aug 11 14:54 generation_config.json
-rw-r--r-- 1 xxx xxx        7020 Aug 11 14:54 LICENSE.txt
-rw-r--r-- 1 xxx xxx  9976578928 Aug 11 14:54 model-00001-of-00002.safetensors
-rw-r--r-- 1 xxx xxx  3500297344 Aug 11 14:54 model-00002-of-00002.safetensors
-rw-r--r-- 1 xxx xxx       26788 Aug 11 14:50 model.safetensors.index.json
-rw-r--r-- 1 xxx xxx 17044209664 Aug 11 14:56 pytorch_model.bin
-rw-r--r-- 1 xxx xxx       26788 Aug 11 14:54 pytorch_model.bin.index.json
-rw-r--r-- 1 xxx xxx       10268 Aug 11 14:53 README.md
-rw-r--r-- 1 xxx xxx     1253223 Aug 11 14:54 Responsible-Use-Guide.pdf
-rw-r--r-- 1 xxx xxx         435 Aug 11 14:54 special_tokens_map.json
-rw-r--r-- 1 xxx xxx         746 Aug 11 14:54 tokenizer_config.json
-rw-r--r-- 1 xxx xxx     1842764 Aug 11 14:54 tokenizer.json
-rw-r--r-- 1 xxx xxx      499723 Aug 11 14:50 tokenizer.model
-rw-r--r-- 1 xxx xxx        4766 Aug 11 14:54 USE_POLICY.md

And the content of config file.

{
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 2048,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pad_token_id": 0,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.31.0.dev0",
  "use_cache": true,
  "vocab_size": 32000
}
