### ISSUE TITLE
我希望获得原始的logits。应该是使用哪个api

### ISSUE THREAD

**Issue by harvinyou** [ModelTC/lightllm#398]
我希望获取当前的模型在我的groundtruth的语句的困惑度，需要获得output前的logits

**Comment by hiworldwzj** [comment]
用 --return_all_prompt_logprobs启动 会返回相关信息，帮助你去计算ppl困惑度。

**Comment by harvinyou** [comment]
非常感谢您的回复，我马上测试一下，想问一下您提供的这个参数控制我在哪里可以查看到



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hiworldwzj ***@***.***&gt;
发送时间: 2024年4月17日 14:42
收件人: ModelTC/lightllm ***@***.***&gt;
抄送: harvinyou ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ModelTC/lightllm] 我希望获得原始的logits。应该是使用哪个api (Issue #398)





 
用 --return_all_prompt_logprobs启动 会返回相关信息，帮助你去计算ppl困惑度。

**Comment by harvinyou** [comment]
> 用 --return_all_prompt_logprobs启动 会返回相关信息，帮助你去计算ppl困惑度。

你好，我加了这个参数，请问一下这个结果是保存在哪里呢，我希望在client中获得这个结果

**Comment by hiworldwzj** [comment]
@harvinyou  generate 接口， 调用之后，你观察一下就明白了。

**Comment by hiworldwzj** [comment]
@harvinyou 信息存在访问的返回的一些字段中。

**Comment by harvinyou** [comment]
return_all_prompt_logprobs 您好，我希望获得生成内容的logics

**Comment by harvinyou** [comment]
> 用 --return_all_prompt_logprobs启动 会返回相关信息，帮助你去计算ppl困惑度。

您好，我发现只能返回输出结果的token_ID 对应的logprob

> 用 --return_all_prompt_logprobs启动 会返回相关信息，帮助你去计算ppl困惑度。

我想要的是和llama2原来代码一致的的输出的logprobs，这里面参数all_prompt_logprobs，我不太理解是不是和llama2一样的
