### ISSUE TITLE
Does lightllm support Qwen-7B deployment?

### ISSUE THREAD

**Issue by songkq** [ModelTC/lightllm#40]

**Comment by hiworldwzj** [comment]
@songkq  Qwen-7 has been supported, you can try.

**Comment by songkq** [comment]
@hiworldwzj Thanks.

 My server crashed when receiving request.  Could you please give some advice for this issue?

```
name, asm, shared_mem = _triton.code_gen.compile_ttir(backend, module, device, num_warps, num_stages, extern_libs, cc)
RuntimeError: Triton requires CUDA 11.4+
DEBUG:MODELRPCSERVER/10017:Exception caught
Traceback (most recent call last):
  File "<string>", line 21, in _rms_norm_fwd_fused
KeyError: ('2-.-0-.-0-05cd73e2a4bdbeb71ab52fd66d1a1ac4-2b0c5161c53c71b37ae20a9996ee4bb8-c1f92808b4e4644c1732e8338187ac87-d962222789c30252d492a16cca3bf467-12f7ac1ca211e037f62a7c0c323d9990-5c5e32ff210f3b7f56c98ca29917c25e-06f0df2d61979d629033f4a22eff5198-0dd03b0bd512a184b3512b278d9dfa59-d35ab04ae841e2714a253c523530b071', (torch.float16, torch.float16, torch.float16, 'i32', 'i32', 'fp32'), (16384,), (True, True, True, (True, False), (True, False), (False,)))

...

  name, asm, shared_mem = _triton.code_gen.compile_ttir(backend, module, device, num_warps, num_stages, extern_libs, cc)
RuntimeError: Triton requires CUDA 11.4+
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-6' coro=<RouterManager.loop_for_fwd() done, defined at /ssd7/exec/songkaiqiang/aigc_repos/llm_inference/lightllm/lightllm/server/router/manager.py:83> exception=Triton requires CUDA 11.4+



```


```
### env: RTX 3090 GPU
### conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia
### triton==2.0.0.dev20221202 

CUDA_VISIBLE_DEVICES="3,4" python -u -m lightllm.server.api_server --model_dir model_repos/Qwen-7B --tokenizer_mode slow --trust_remote_code --tp 2 --port 8099 \
  --max_req_total_len 4096 --max_req_input_len 3600 --running_max_req_size 4 --max_total_token_num 30000 --eos_id 151643 > logs/server_run_qwen_7b.log 2>&1 &
```

**Comment by llehtahw** [comment]
@songkq could you please show me the output of the following command?

```
which ptxas
ptxas --version
```

**Comment by songkq** [comment]
@llehtahw  
```
ptxas: NVIDIA (R) Ptx optimizing assembler
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:09:21_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0
```

**Comment by llehtahw** [comment]
> @llehtahw
> 
> ```
> ptxas: NVIDIA (R) Ptx optimizing assembler
> Copyright (c) 2005-2020 NVIDIA Corporation
> Built on Tue_Sep_15_19:09:21_PDT_2020
> Cuda compilation tools, release 11.1, V11.1.74
> Build cuda_11.1.TC455_06.29069683_0
> ```

Seems your cuda toolkit version is 11.1, but the minimum required version is 11.4, see https://github.com/ModelTC/lightllm/issues/40#issuecomment-1674346476

> RuntimeError: Triton requires CUDA 11.4+

Consider using cuda 11.8 @songkq

**Comment by hiworldwzj** [comment]
@songkq  please update latest code for qwen-7b, #55

**Comment by hiworldwzj** [comment]
@songkq it looks like tp error,  you can try use "--tp 1",  I have test it before.

**Comment by hiworldwzj** [comment]
@songkq  I have fixed this bug， #60 ， you can pull latest code.

**Comment by songkq** [comment]
@hiworldwzj Good job! I'll try it. By the way, did you verify the accuracy of Qwen results generated by `lightllm` compared with `huggingface`?

**Comment by hiworldwzj** [comment]
@songkq I try a simple test, it looks like right. But now only support 2k length,  I will try to fix to support 8k length.

**Comment by songkq** [comment]
@hiworldwzj Hi, dose it support 4k context now?

**Comment by hiworldwzj** [comment]
@songkq  The code can run, but because the NTK mechanism has not been implemented, accuracy may not be guaranteed. I have tried an 8k static NTK, but I feel that its performance is not great for long sentences, so I didn't merge the code into master.

**Comment by songkq** [comment]
@hiworldwzj Thanks.
