### ISSUE TITLE
如何支持模型输出一个特定的output的困惑度

### ISSUE THREAD

**Issue by harvinyou** [ModelTC/lightllm#401]
特定的output是ground-truth，如何计算生成ground-truth的ppl呢

**Comment by hiworldwzj** [comment]
将输入和ouput拼接成输入，用--return_all_prompt_logprobs启动，然后就能得到了吧。

**Comment by harvinyou** [comment]
好的谢谢您
---- 回复的原邮件 ----
***@***.***>发送日期2024年04月24日 09:59 ***@***.***> ***@***.***>,
***@***.***>主题Re: [ModelTC/lightllm] 如何支持模型输出一个特定的output的困惑度 (Issue #401)
将输入和ouput拼接成输入，用--return_all_prompt_logprobs启动，然后就能得到了吧。

**Comment by hiworldwzj** [comment]
@harvinyou 不过我好像记得不是所有模型都支持 --return_all_prompt_logprobs 这个。
