### ISSUE TITLE
关于多并发时，batch_size的调整

### ISSUE THREAD

**Issue by zackdist** [ModelTC/lightllm#41]
![1691636049593](https://github.com/ModelTC/lightllm/assets/77257102/44d0f349-2070-44b7-b954-950dd8119650)
请问上图中的 batch_size : 4 token 能否通过什么配置或者代码进行调整呢？
想要更大的batch_size尝试。

**Comment by hiworldwzj** [comment]
这个运行的batch是router通过容量动态调整的，如果你的显卡容量足，可以设置一个合理的max_total_token_num 来使其容量更大，同时请求的输出长度不要设置得过长，就可以得到更大的并发。

**Comment by zackdist** [comment]
好的好的
