### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by lucasjinreal** [ModelTC/lightllm#44]
triton/compiler/compiler.py", line 18, in <module>
    from ..runtime.autotuner import OutOfResources
ImportError: cannot import name 'OutOfResources' from partially initialized module 'triton.runtime.autotuner' (most likely due to a circular import) (

**Comment by hiworldwzj** [comment]
@lucasjinreal 能不能给一个详细的环境信息。

**Comment by lucasjinreal** [comment]
我就是直接clone 最新的代码 pip install -e .

run:

```
python -m lightllm.server.api_server --model_dir baichuan-13B-v2-1500 -tp 2 --max_total_token_num 120000
```
就这样了。

看起来是一个triton API没有对齐的问题？

**Comment by hiworldwzj** [comment]
@lucasjinreal 你用得什么 gpu 呀？ baichuan 模型不知道能不能支持额。

**Comment by lucasjinreal** [comment]
v100，看起来是一个python接口循环导入的问题。

**Comment by hiworldwzj** [comment]
@lucasjinreal 我们内部跑过 V100 虽然能跑起来，但是 triton kernel 存在计算精度的问题，很尴尬。建议在安倍架构的芯片上跑，问题少很多。

**Comment by lucasjinreal** [comment]
很尴尬，穷的人只有v1--

**Comment by hiworldwzj** [comment]
@lucasjinreal 很大，几乎不可用，主要出在 context_flash_attention 这个算子上。最近triton 2.1.0的更新太不稳定了，不太敢用最新版本，只有等triton稳定下来。如果确实想跑，你需要把这个算子实现成pytorch的形式或用其他方法实现。

**Comment by lucasjinreal** [comment]
感谢，这么说v100下还是vllm比较靠谱，有比vllm更快的方案吗

**Comment by hiworldwzj** [comment]
@lucasjinreal 没办法，triton的不稳定，带来了太多的约束，其实你可以尝试最新版本的TGI.不过TGI 部署起来麻烦些，也很不错。

**Comment by lucasjinreal** [comment]
TGI也是vllm inside，我目前遇到的问题是vllm 在v100上的推理结果，参数一致的情况下，似乎跟huggingface transformers 存在比较大的差距。

**Comment by hiworldwzj** [comment]
@lucasjinreal 这个我就不是很清楚了，TGI 后台也就几个 vllm flash attention 算子, 可能存在一些精度上的问题吧。你也可以看一下是不是默认的采样参数不太一样导致的。

**Comment by hiworldwzj** [comment]
@lucasjinreal 我们这边有个兄弟找到修改V100 上算子，让其没有精度问题的方法了，明天应该可以验证上库。到时候你可以尝试一下。

**Comment by lucasjinreal** [comment]
@hiworldwzj 可以，顺便记得分享一下加速比

**Comment by hiworldwzj** [comment]
@lucasjinreal 代码已经修改了 #53 ， 你可以试试看，现在手里面没有V100，还没有跑性能数据。
