### ISSUE TITLE
启动服务报错不支持llama怎么操作才能支持llama呀？感谢

### ISSUE THREAD

**Issue by wll-design** [ModelTC/lightllm#445]
![image](https://github.com/ModelTC/lightllm/assets/173032835/be936506-76be-4bf1-abd0-096d77cd0372)

**Comment by hiworldwzj** [comment]
@wll-design 你是要启动llava模型？

**Comment by shihaobai** [comment]
如果不是 多模态的模型的话，启动的时候，不需要添加 --enable_multimodal
