### ISSUE TITLE
[BUG] _rms_norm_fwd_fused triton kernel 初始化参数混乱

### ISSUE THREAD

**Issue by Biubiubiu12** [ModelTC/lightllm#449]
> M, N = x_arg.shape
    # Less than 64KB per feature: enqueue fused kernel
    MAX_FUSED_SIZE = 65536 // x.element_size()
    BLOCK_SIZE = min(MAX_FUSED_SIZE, triton.next_power_of_2(N))
    # print("BLOCK_SIZE:", BLOCK_SIZE)
    if N > BLOCK_SIZE:
        raise RuntimeError("This layer norm doesn't support feature dim >= 64KB.")
    # heuristics for number of warps
    num_warps = min(max(BLOCK_SIZE // 256, 1), 8)
    # print(BLOCK_SIZE, num_warps, "block_size, numwarps")
    BLOCK_SIZE = 128 * 2 * 2 * 2 * 2 * 2 * 2 * 2
    num_warps = 8

详见[https://github.com/ModelTC/lightllm/blob/b35405c0038ae92f4561c19f9dfc124feaa49d36/lightllm/models/llama/triton_kernel/rmsnorm.py#L59](url)
请问BLOCK_SIZE 和num_warps 设置的依据是什么呢？ @XHPlus

**Comment by hiworldwzj** [comment]
@Biubiubiu12 这个算子因为不是关键的性能瓶颈算子，就写成能支持比较大size的支持形式，有些遗留没有清理。 block_size 和 num_warps 的最佳设置可能需要对其内部原理比较清楚来弄。如果想调优就直接用triton 的tuning 方式把，帮你直接搜索最优的配置，详细可以去看triton的官方文档。

**Comment by Biubiubiu12** [comment]
> @Biubiubiu12 这个算子因为不是关键的性能瓶颈算子，就写成能支持比较大size的支持形式，有些遗留没有清理。 block_size 和 num_warps 的最佳设置可能需要对其内部原理比较清楚来弄。如果想调优就直接用triton 的tuning 方式把，帮你直接搜索最优的配置，详细可以去看triton的官方文档。

好的，感谢回复🙏
