### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by UncleFB** [ModelTC/lightllm#45]
1. `docker build -t lightllm_v1 . --network host --build-arg http_proxy=http://127.0.0.1:7890 --build-arg https_proxy=http://127.0.0.1:7890`
2. `docker run -itd --gpus all --network=host -v /data/public_file:/data/ --name lightllm_test lightllm_v1`
3. get into container and execute 
`python -m lightllm.server.api_server --model_dir /data/LLM_model/Llama2-Chinese-7b-Chat/ --tp 1 --max_total_token_num 120000`

```
root@dell:/usr/src# python -m lightllm.server.api_server --model_dir /data/LLM_model/Llama2-Chinese-7b-Chat/ --tp 1 --max_total_token_num 120000
Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Process Process-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/lightllm/server/router/manager.py", line 243, in start_router_process
    asyncio.run(router.wait_to_model_ready())
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/conda/lib/python3.9/site-packages/lightllm/server/router/manager.py", line 57, in wait_to_model_ready
    await asyncio.gather(*init_model_ret)
  File "/opt/conda/lib/python3.9/site-packages/lightllm/server/router/model_infer/model_rpc.py", line 179, in init_model
    ans : rpyc.AsyncResult = self._init_model(rank_id, world_size, weight_dir, max_total_token_num, load_way, mode)
  File "/opt/conda/lib/python3.9/site-packages/lightllm/server/router/model_infer/model_rpc.py", line 34, in exposed_init_model
    dist.init_process_group('nccl', init_method=f'tcp://127.0.0.1:{setting["nccl_port"]}', rank=rank_id, world_size=world_size)
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 895, in init_process_group
    default_pg = _new_process_group_helper(
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 998, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.9/site-packages/lightllm/server/router/manager.py", line 246, in start_router_process
    router.clean_up()
  File "/opt/conda/lib/python3.9/site-packages/lightllm/server/router/manager.py", line 223, in clean_up
    model_rpc.rpc_server_process.kill()
AttributeError: 'NoneType' object has no attribute 'kill'
Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
router init state: Distributed package doesn't have NCCL built in detoken init state: init ok
```

**Comment by shihaobai** [comment]
Thank you for your pointing out! Can you provide more details of your device?

**Comment by UncleFB** [comment]
> Thank you for your pointing out! Can you provide more details of your device?

NVIDIA GeForce RTX 3090
NVIDIA-SMI 525.116.03   
Driver Version: 525.116.03   
CUDA Version: 12.0

**Comment by llehtahw** [comment]
i’m working on it, you can try this package and its dockerfile. currently it’s not tested
@UncleFB 

`docker pull ghcr.io/llehtahw/lightllm:main`

https://github.com/llehtahw/lightllm/blob/main/Dockerfile

**Comment by UncleFB** [comment]
Thank you very much!
I pull that image. And build by that Dockerfile, it works now.
After that, I ran into another problem.
In fact, there are eight graphics cards, the total memory is definitely enough, but I don't know how to configure it to load the model successfully.

```
root@dell:/usr/src# python -m lightllm.server.api_server --model_dir /data/LLM_model/Llama2-Chinese-7b-Chat --tp 1 --max_total_token_num 120000
Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Process Process-1:
router init state: CUDA out of memory. Tried to allocate 938.00 MiB (GPU 0; 23.69 GiB total capacity; 17.41 GiB already allocated; 284.94 MiB free; 17.41 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF detoken init state: init ok
```

**Comment by UncleFB** [comment]
> Thank you very much! I pull that image. And build by that Dockerfile, it works now. After that, I ran into another problem. In fact, there are eight graphics cards, the total memory is definitely enough, but I don't know how to configure it to load the model successfully.
> 
> ```
> root@dell:/usr/src# python -m lightllm.server.api_server --model_dir /data/LLM_model/Llama2-Chinese-7b-Chat --tp 1 --max_total_token_num 120000
> Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
> Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
> Process Process-1:
> router init state: CUDA out of memory. Tried to allocate 938.00 MiB (GPU 0; 23.69 GiB total capacity; 17.41 GiB already allocated; 284.94 MiB free; 17.41 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF detoken init state: init ok
> ```
实际上我们的机器上有八张显卡，内存应该是够用的，怎么配置能加载成功呢

**Comment by UncleFB** [comment]
root@dell:/usr/src# python -m lightllm.server.api_server --model_dir /data/LLM_model/Llama2-Chinese-7b-Chat --tp 1
clean
Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Process Process-1:
router init state: 'NoneType' object has no attribute 'get' detoken init state: init ok

**Comment by hiworldwzj** [comment]
@UncleFB Can you show config.json of this model?

**Comment by llehtahw** [comment]
Hi @UncleFB 

I've uploaded a new image with its code, that might help you locate the error

> `docker pull ghcr.io/llehtahw/lightllm:main`
> 
> https://github.com/llehtahw/lightllm/blob/main/Dockerfile

**Comment by hiworldwzj** [comment]
@UncleFB 我已经修复了这个bug， 你可以用最新的代码安装运行。 代码 #50

**Comment by UncleFB** [comment]
感谢，成功了，🐮
