### ISSUE TITLE
计划什么时候支持baichuan-13b-chat ？

### ISSUE THREAD

**Issue by Zhang-star-master** [ModelTC/lightllm#48]
计划什么时候支持baichuan-13b-chat呢  期待早点支持可以测试下推理性能

**Comment by hiworldwzj** [comment]
@Zhang-star-master Baichuan 看起来其结构和 llama 几乎一模一样。

https://github.com/ModelTC/lightllm/blob/main/lightllm/server/router/model_infer/model_rpc.py#L46

感觉把这一行改成 baichuan 就可能能跑，不然再修改修改 config.json 中的一些key的名字。

**Comment by hiworldwzj** [comment]
@Zhang-star-master  #52  这个地方有新的异常发现需要处理。

**Comment by hiworldwzj** [comment]
@Zhang-star-master  Baichuan has been supported, code is #67,  only test Baichuan-7B, you can Try it.

**Comment by Hap-Zhang** [comment]
@hiworldwzj Hi, it seems some difference between Baichuan-13B and Baichuan-7B in position encoding.  I think it should not be directly compatible with Baichuan-7B.
![image](https://github.com/ModelTC/lightllm/assets/32810063/814ce741-10e0-4978-a250-88afc7423fc6)

**Comment by hiworldwzj** [comment]
@Hap-Zhang  I didn't even notice this.  It's confusing when the same model is used with different architectures. I will try to fix this.

**Comment by Hap-Zhang** [comment]
@hiworldwzj OK, thank you very much for your effort.

**Comment by hiworldwzj** [comment]
@Hap-Zhang  Baichuan13B is Ok, you can try it.
