### ISSUE TITLE
What team are the developers from?

### ISSUE THREAD

**Issue by CSEEduanyu** [ModelTC/lightllm#502]
The architecture of sglang is very similar to lightllm. Is there any connection between the two?

**Comment by XHPlus** [comment]
The core contributors are from the Model Toolchain (MTC) team of SenseTime Research.

Regarding SGLang, as indicated in the README, they reused some codes from LightLLM. In fact, we have very close communication with SGLang's authors, such as Lianmin. They supplement new features like RadixAttention at the base of LightLLM and achieve further performance improvement. With both project's efforts, we believe the community will advance more rapidly.

<img width="841" alt="image" src="https://github.com/user-attachments/assets/6d3c616b-5171-45f7-99ba-88ac886a57c3">
