### ISSUE TITLE
benchmark无法完整运行

### ISSUE THREAD

**Issue by HuaYZhao** [ModelTC/lightllm#54]
再次压测时发现，最新的代码在按照readme运行以下代码时无法成功：
![image](https://github.com/ModelTC/lightllm/assets/37064550/e9cd61a1-05bc-40d9-ae8c-6234ae2347d5)
显卡：A100
模型：llama-7b-hf
出现的现象为：服务不断出现接收http的请求，但是显示batch token及token ratio的日志不再出现且gpu利用率为0，这有理由说明推理已经完成？值得一提的是最开始时batch token的日志是出现的，并且token ratio占比很高。
![image](https://github.com/ModelTC/lightllm/assets/37064550/80cabbbe-866d-4cbb-b527-7e695256e49d)

等待很久之后，终于返回了benchmark的结果，但这相比预期差了许多，在后面的很长一段时间，gpu的利用率一直为0！我怀疑服务已经完成推理，但引擎未发起正确的返回。
![image](https://github.com/ModelTC/lightllm/assets/37064550/73eaca69-f5c5-45e3-96bb-1cc990ac2849)

期待您的回复~

**Comment by hiworldwzj** [comment]
@HuaYZhao 经典问题，没有加载 fast tokenizer。

**Comment by hiworldwzj** [comment]
@HuaYZhao  https://github.com/ModelTC/lightllm/issues/20#issuecomment-1673558881
#20   你看一下这两个

**Comment by HuaYZhao** [comment]
@hiworldwzj  是的，它很好的解决了问题！
