### ISSUE TITLE
如果不想要进行batch推理的话应该怎么办？

### ISSUE THREAD

**Issue by Chen8566** [ModelTC/lightllm#601]
lightllm进行部署后，如果同时有多个请求进来，lightllm会默认进行batch推理，但是我不希望进行batch，而是希望每个请求是一个单独的进程，这应该怎么办？

**Comment by Chen8566** [comment]
有没有参数可以控制？

**Comment by hiworldwzj** [comment]
@Chen8566  有，--running_max_req_size 1 启动的时候设置这个为1，调度的时候就会限制运行batch size 最大为1.
