### ISSUE TITLE
Cannot use NsightSystems to trace gpu usage

### ISSUE THREAD

**Issue by leiwen83** [ModelTC/lightllm#64]
Hi,

I try use nsys profile to trace the detail of gpu usage, but fail to capture any gpu thread.
For other gpu env, the profile works ok, and I also could use nsys for vllm.

So I wonder why nsys cannot trace lightllm?

Thx

**Comment by hiworldwzj** [comment]
@leiwen83 I guess that triton kernel is lazy compile to load?

**Comment by leiwen83** [comment]
seem --trace-fork-before-exec in nsys need to be for lightllm trace, with this flag, cuda kernel is captured
