### ISSUE TITLE
Support OpenAI-Compatible APIs

### ISSUE THREAD

**Issue by merrymercy** [ModelTC/lightllm#65]
A lot of existing code uses the OpenAI API, could you also support this?

For example, FastChat and vLLM both provide OpenAI-compatible API servers (https://github.com/lm-sys/FastChat/blob/main/docs/openai_api.md).

**Comment by XHPlus** [comment]
Hi Lianmin, Thanks for your suggestion. We will add support for the standard OpenAI API to make it compatible with FastChat and vLLM format.

**Comment by huanglx27** [comment]
> Hi Lianmin, Thanks for your suggestion. We will add support for the standard OpenAI API to make it compatible with FastChat and vLLM format.

Function openai.ChatCompletion.create(model, messages, stream)  can pass history message. Will open LLM like Chatglm be able to use it ?
