### ISSUE TITLE
[BUG] encountering conflicting dependencies when builting from source

### ISSUE THREAD

**Issue by MisterBrookT** [ModelTC/lightllm#676]
I have searched the related issue though keyword matching. 

when i use the commands from docs (https://lightllm-cn.readthedocs.io/en/latest/getting_started/installation.html),  conflict happens(see below), 

<img width="833" alt="image" src="https://github.com/user-attachments/assets/75a0a6af-ac6b-4ff7-874a-e6e86f91aeb5" />

**Comment by hiworldwzj** [comment]
@MisterBrookT  you can ignore this error and install tokenizer by yourself. we will fix this soon.

**Comment by hiworldwzj** [comment]
@MisterBrookT #677 ok now.
