### ISSUE TITLE
输入参数问题

### ISSUE THREAD

**Issue by UncleFB** [ModelTC/lightllm#71]
![image](https://github.com/ModelTC/lightllm/assets/38581531/eb3bd261-2887-41ee-93d1-775fe8748ae2)
我看 llama2-chinese 的输入 prompt 是这种，如何使用lightllm达到同样的效果嘞

**Comment by llehtahw** [comment]
@UncleFB 你可以在调用lightllm http api时自行拼接合适的prompt

**Comment by hiworldwzj** [comment]
@UncleFB 直接把这段字符串，输入到输入里。

**Comment by UncleFB** [comment]
返回的结果好像不太符合预期，原版的 tokenizer 里面有一些参数，不知道是否有影响
具体有这里
`input_ids = tokenizer(['<s>Human: xxx\n</s><s>Assistant: '], return_tensors="pt",add_special_tokens=False).input_ids.to('cuda')`
还有这里
![image](https://github.com/ModelTC/lightllm/assets/38581531/8fea1d02-72a7-480d-b72d-e636e4474d39)

**Comment by hiworldwzj** [comment]
是这个 add_special_tokens 参数不一样导致的吗？

**Comment by hiworldwzj** [comment]
@UncleFB 看你贴的代码，采样参数也是很大的不同呀

**Comment by UncleFB** [comment]
![image](https://github.com/ModelTC/lightllm/assets/38581531/4a08b453-238c-43a6-9320-f9ed58ad7d99)
![image](https://github.com/ModelTC/lightllm/assets/38581531/87fd9caa-da8f-4e4a-adb8-820a06df523e)

**Comment by hiworldwzj** [comment]
@UncleFB 可以贴一下这两个的输出吗，可以试试把 do_sample 设置成 False试试， 如果两边的随机种子不一样，在采样的时候可能会出现不同的答案。

**Comment by UncleFB** [comment]
![image](https://github.com/ModelTC/lightllm/assets/38581531/d3356b08-7cb2-4fbf-9235-45c583ddc710)
![image](https://github.com/ModelTC/lightllm/assets/38581531/fe66a132-fe2b-43fd-b646-af2eeb1d7d12)

**Comment by hiworldwzj** [comment]
@UncleFB 两边用的penalty 参数没有对齐。

**Comment by UncleFB** [comment]
![Uploading image.png…]()

**Comment by UncleFB** [comment]
![image](https://github.com/ModelTC/lightllm/assets/38581531/bf5cdc17-b7cf-4dcb-9d5e-a1c4d16902e5)
我看lightllm的代码里只有这两种 penalty ，并没有 repetition_penalty

**Comment by hiworldwzj** [comment]
@UncleFB 以前在选择实现惩罚机制的时候考虑过你用的这种，但是感觉你用的这种实现上很不优雅，所以就选择了现在的方案。我个人觉得现在的这种要好一些。不知你是否能提供必须支持你用的这种惩罚机制的理由，我们会快速填加，实现也很容易

**Comment by UncleFB** [comment]
没有特别的理由，只是看到Llama2官方的例子是这样设置参数的，想看一下使用lightllm加速后返回的结果是否还能符合预期。非常感谢您的解答，想问一下，我们是否有群组之类的方便沟通交流呀

**Comment by llehtahw** [comment]
> 想问一下，我们是否有群组之类的方便沟通交流呀

@UncleFB 可以加入新鲜的discord https://discord.gg/WzzfwVSguU
