### ISSUE TITLE
当我执行abort之后，请求是否会立马被终止？

### ISSUE THREAD

**Issue by HuaYZhao** [ModelTC/lightllm#75]
当我传入一个生成很长的请求时，如生成1280个tokens，然后中断请求，我观察到服务执行了abort命令，但同时观察到gpu利用率并没有马上为0，并且需要等待不少时间才会为0！

**Comment by hiworldwzj** [comment]
@HuaYZhao 这个 abort 机制实现得有点复杂和丑陋，以前测试的时候，应该是可以中途退出请求的，可能还有bug。可以给个复现的步骤吗，我们修一下。

**Comment by HuaYZhao** [comment]
是的，在我之前的测试中，这个功能是可以正常工作的:)；复现只需要在https://github.com/ModelTC/lightllm/blob/main/lightllm/server/router/manager.py#L102C1-L106C32 这几行中间打印一些日志，就可以进行观察；比如添加以下代码
```
print('running_batch:', len(self.running_batch.reqs) if self.running_batch else 0)
if self.running_batch:
    print('output_ids_len', len(self.running_batch.reqs[0].output_ids), self.running_batch.reqs[0].aborted)
```

**Comment by HuaYZhao** [comment]
已经解决了吗？

**Comment by hiworldwzj** [comment]
@HuaYZhao Hello, 最近在重构代码，现在已经修复了这个bug了，代码在这里 #91,  久等了哈。你可以试试看。
