### ISSUE TITLE
lightllm vs vllm

### ISSUE THREAD

**Issue by tonylin52** [ModelTC/lightllm#79]
Hi,

I am testing the benchmark between lightllm and vllm, it seems that vllm achieves better results of 'token/ms' for llama 30b.

Here are the parameters for lightllm and vllm server:
![image](https://github.com/ModelTC/lightllm/assets/31800397/af3d041f-db0c-4af2-89cf-6baed9868beb)
![image](https://github.com/ModelTC/lightllm/assets/31800397/56d31571-a2eb-40b0-b727-f64a78cd263f)

**Comment by hiworldwzj** [comment]
@tonylin52  我简单说明一下，用英文可能说不太清楚。 其实这是可能的，目前细节上的问题我们都掌握了。可能的原因如下：
1 在使用了 int8kv cache 的时候，因为这个特性的算子triton没有优化好，只能在一些低端的卡上跑小一些的模型来提升吞吐，但是这个特性因为算子性能太差，单个token的生成延迟确实会很大， 这个需要等到triton的优化和提升了。
2. lightllm 的后台并发可能可以容纳更多的用户进行一起合并推理，导致延迟稍微大一些。
3. 显卡的问题，目前的triton kernel 所用的配置是在 A800 上精细调整过的，所以在一些其他卡上，如果想得到最佳的性能可能需要调整triton kernel 的配置。
4. 还有一个问题是目前 lightllm 的decode attention 算子性能上不是特别好，有两个方面的原因，第一个是写法上的问题，第二个是triton的问题。 当triton 2.0.0 升级 到 2.1.0 以后， （目前 triton 2.1.0 还没有官方发布版本）我们会修复这个问题，那个时候可以得到一个非常完美的性能。

**Comment by tonylin52** [comment]
> @tonylin52 我简单说明一下，用英文可能说不太清楚。 其实这是可能的，目前细节上的问题我们都掌握了。可能的原因如下： 1 在使用了 int8kv cache 的时候，因为这个特性的算子triton没有优化好，只能在一些低端的卡上跑小一些的模型来提升吞吐，但是这个特性因为算子性能太差，单个token的生成延迟确实会很大， 这个需要等到triton的优化和提升了。 2. lightllm 的后台并发可能可以容纳更多的用户进行一起合并推理，导致延迟稍微大一些。 3. 显卡的问题，目前的triton kernel 所用的配置是在 A800 上精细调整过的，所以在一些其他卡上，如果想得到最佳的性能可能需要调整triton kernel 的配置。 4. 还有一个问题是目前 lightllm 的decode attention 算子性能上不是特别好，有两个方面的原因，第一个是写法上的问题，第二个是triton的问题。 当triton 2.0.0 升级 到 2.1.0 以后， （目前 triton 2.1.0 还没有官方发布版本）我们会修复这个问题，那个时候可以得到一个非常完美的性能。

收到！谢谢

**Comment by Tracin** [comment]
@tonylin52 Hi, What if run without `mode=int8kv` ? For computation-bounded situation(with sufficient memory), this may course worse performance. Can we get any detailed results? Since we really concerned about the performance.

**Comment by tonylin52** [comment]
Actually, I tied lightllm without int8kv 

Here are some of the benchmark results we have tested:
llama-30b, 1xA100 80G, CUDA-11.7, Number of user requests: 5


Num of input token:32
Num of output token:512
vllm 20.45 token/s per user
lightllm 18.78 token/s per user

Num of input token:1024
Num of output token:1024
vllm 14.81 token/s per user
lightllm 12.04 token/s per user

Num of input token:2048
Num of output token:32
vllm 5.68 token/s per user
lightllm 5.25 token/s per user

**Comment by hiworldwzj** [comment]
@tonylin52 Thanks, triton 2.1.0 can be better, but need to modify some source code of triton.

**Comment by tonylin52** [comment]
> @tonylin52 Thanks, triton 2.1.0 can be better, but need to modify some source code of triton.

May I ask if you could provide the modified triton code? Thanks!
