### ISSUE TITLE
[BUG]No module named 'lightllm.models.chatglm2.triton_kernel

### ISSUE THREAD

**Issue by glsoon** [ModelTC/lightllm#83]
执行的是百川13b模型，命令和报错如下，辛苦看下如何解决。

python -m lightllm.server.api_server --model_dir output_dir_0728/global_step_e3_60344     \
                                     --host 0.0.0.0                 \
                                     --port 3302                    \
                                     --tp 1                         \
                                     --trust_remote_code             \
                                     --max_total_token_num 1500

<img width="1035" alt="image" src="https://github.com/ModelTC/lightllm/assets/20046142/922a1983-784d-4047-843e-c37ba288074f">

**Comment by hiworldwzj** [comment]
@glsoon 百川13b 现在应该还不能支持，看这个代码你咋跑到 chatglm2 的代码里去了。明天我会把百川13b加好。

**Comment by hiworldwzj** [comment]
@glsoon 最近在重构代码，以后会出文档指导如何添加模型。

**Comment by glsoon** [comment]
辛苦了，老哥

**Comment by hiworldwzj** [comment]
@glsoon  最新的代码支持了 baichuan13b， 你要注意自己生成的模型权重名称是不是和代码里面写的一致呀，我们是按照huggingface上的标准名称和格式来加载的。

**Comment by singularity-s0** [comment]
@hiworldwzj 这个问题的原因是安装程序`python setup.py install`复制文件时有遗漏，可以尝试如下步骤复现：
1. 建一个新的conda环境并安装lightllm
2. 如果当前工作目录是setup.py所在的文件夹，那么lightllm可以正常启动
3. 如果当前工作目录是其他目录（比如cd到根目录），那么启动lightllm时会出现以上报错。

**Comment by singularity-s0** [comment]
已在 PR #94 中修复
