### ISSUE TITLE
[BUG]llama2-70B 加载完成后，无法启动服务

### ISSUE THREAD

**Issue by ChristineSeven** [ModelTC/lightllm#88]
机器 A100 80G *3
启动命令：python -m lightllm.server.api_server --model_dir /path_to/Llama-2-70b-hf --tp 2 --max_total_token_num 120000 --max_req_input_len 3000 --max_req_total_len 4096
CUDA_V 11.8
python 3.9

模型权重加载卡住，有两张卡被使用，每张卡上面大概30多G现存，然后就一直卡住了。一直起不来服务。

log如下：
Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
^[[M`T2^[[M`T2

**Comment by hiworldwzj** [comment]
@ChristineSeven 应该有具体的错误信息打印呀，后面乱码部分可以贴一下吗

**Comment by ChristineSeven** [comment]
没有错误打印，最后一句是这个。Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead。乱码部分跟这个没关系，是键盘输入。

**Comment by ChristineSeven** [comment]
stucked here. 
   # wait load model ready
    router_init_state = pipe_router_reader.recv()
    detoken_init_state = pipe_detoken_reader.recv()

**Comment by hiworldwzj** [comment]
@ChristineSeven 我测试的时候用的llama2 70b chat

**Comment by ChristineSeven** [comment]
@hiworldwzj The same issue for Llama-2-70b-chat-hf model.

**Comment by hiworldwzj** [comment]
@ChristineSeven 我用你的启动配置在llama2-70b-chat 上试了一下，我看是ok的呀。如果是每个卡显存加载到30G就不动了，感觉应该是加载权重的过程出了问题了。只是目前我本地没有复现，不是很清楚出问题的原因。你可以尝试一下构建一个干净的环境再试试呢。

**Comment by ChristineSeven** [comment]
@hiworldwzj 这个原因是当config文件配置中存储类型是bfloat16时，加载就会出现问题。目前通过转换可以解决这个问题。我们是否打算支持一下其他存储类型呢？

**Comment by ChristineSeven** [comment]
存储类型的区别导致加载失败。
