### ISSUE TITLE
[BUG] triton version confict 

### ISSUE THREAD

**Issue by fredbjer** [ModelTC/lightllm#95]
**Before you submit an issue, please search for existing issues to avoid duplicates.**

**Issue description:**
`pip install requirements.txt` occurs error below:

```
INFO: pip is looking at multiple versions of torch to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 64) and triton==2.0.0.dev20221202 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested triton==2.0.0.dev20221202
    torch 2.0.0 depends on triton==2.0.0; platform_system == "Linux" and platform_machine == "x86_64"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

does the triton version must use `2.0.0.dev20221202` exactly ?

**Comment by hiworldwzj** [comment]
@fredbjer Yes, but you can also use Triton 2.1.0 version.

**Comment by hiworldwzj** [comment]
@fredbjer This conflict can be ignored. Just make sure to have the right Triton version, the Torch version is not very important.

**Comment by fredbjer** [comment]
> @fredbjer Yes, but you can also use Triton 2.1.0 version.

@hiworldwzj thanks for your reply, i would try to use Triton 2.1.0.
